included:
  - Ramekin
  - RamekinShareExtension
  - Shared
  - RamekinTests

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - closure_spacing
  - discouraged_optional_boolean
  - private_over_fileprivate

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 60
  error: 100

file_length:
  warning: 500
  error: 1000

identifier_name:
  excluded:
    - id
    - ok
    - url
    - recipe_id
    - error_message
