name: Setup
description: Install Rust, uv, and configure caching

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libpq-dev

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: server -> target
        cache-on-failure: true

    - name: Install diesel CLI
      shell: bash
      run: cargo install diesel_cli --no-default-features --features postgres

    - name: Install uv
      uses: astral-sh/setup-uv@v5
