name: Setup
description: Install Rust, Node.js, uv, process-compose, and configure caching

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libpq-dev shellcheck

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          server -> target
          cli -> target
          ramekin-core -> target
        cache-on-failure: true
        cache-all-crates: true

    - name: Install diesel CLI
      shell: bash
      run: cargo install diesel_cli --no-default-features --features postgres

    - name: Install cargo-watch
      shell: bash
      run: cargo install cargo-watch

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: 'npm'
        cache-dependency-path: 'ramekin-ui/package-lock.json'

    - name: Install process-compose
      shell: bash
      run: |
        PC_VERSION=v1.87.0
        PC_URL="https://github.com/F1bonacc1/process-compose/releases/download/${PC_VERSION}"
        curl -fsSL "${PC_URL}/process-compose_linux_amd64.tar.gz" \
          | sudo tar -xzf - -C /usr/local/bin process-compose
        sudo chmod +x /usr/local/bin/process-compose
