name: Setup
description: Install Rust, Node.js, uv, process-compose, and configure caching

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libpq-dev

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: server -> target
        cache-on-failure: true

    - name: Install diesel CLI
      shell: bash
      run: cargo install diesel_cli --no-default-features --features postgres

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"

    - name: Install process-compose
      shell: bash
      run: |
        curl -fsSL https://github.com/F1bonacc1/process-compose/releases/download/v1.51.0/process-compose_linux_amd64.tar.gz | sudo tar -xzf - -C /usr/local/bin process-compose
        sudo chmod +x /usr/local/bin/process-compose
