name: Setup
description: Install Rust, Node.js, uv, process-compose, and configure caching

runs:
  using: composite
  steps:
    - name: Install system dependencies
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y libpq-dev shellcheck

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: |
          server -> target
          cli -> target
          ramekin-core -> target
        cache-on-failure: true
        cache-all-crates: true

    - name: Install cargo-binstall
      shell: bash
      run: |
        curl -L --proto '=https' --tlsv1.2 -sSf \
          https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh \
          | bash

    - name: Install diesel CLI
      shell: bash
      run: cargo binstall diesel_cli --no-default-features --features postgres --no-confirm

    - name: Install ast-grep
      shell: bash
      run: cargo binstall ast-grep --no-confirm

    - name: Install SwiftLint
      shell: bash
      run: |
        SWIFTLINT_VERSION=$(curl -fsSL \
          https://api.github.com/repos/realm/SwiftLint/releases/latest | jq -r .tag_name)
        echo "Installing SwiftLint ${SWIFTLINT_VERSION}"
        SWIFTLINT_URL="https://github.com/realm/SwiftLint/releases/download"
        curl -fsSL "${SWIFTLINT_URL}/${SWIFTLINT_VERSION}/swiftlint_linux_amd64.zip" \
          -o /tmp/swiftlint.zip
        unzip -q /tmp/swiftlint.zip -d /tmp/swiftlint
        sudo mv /tmp/swiftlint/swiftlint /usr/local/bin/swiftlint
        sudo chmod +x /usr/local/bin/swiftlint

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: 'npm'
        cache-dependency-path: 'ramekin-ui/package-lock.json'

    - name: Install process-compose
      shell: bash
      run: |
        PC_VERSION=v1.87.0
        PC_URL="https://github.com/F1bonacc1/process-compose/releases/download/${PC_VERSION}"
        curl -fsSL "${PC_URL}/process-compose_linux_amd64.tar.gz" \
          | sudo tar -xzf - -C /usr/local/bin process-compose
        sudo chmod +x /usr/local/bin/process-compose

    - name: Install mkcert
      shell: bash
      run: |
        MKCERT_VERSION=v1.4.4
        MKCERT_URL="https://github.com/FiloSottile/mkcert/releases/download"
        curl -fsSL "${MKCERT_URL}/${MKCERT_VERSION}/mkcert-${MKCERT_VERSION}-linux-amd64" \
          -o /tmp/mkcert
        sudo mv /tmp/mkcert /usr/local/bin/mkcert
        sudo chmod +x /usr/local/bin/mkcert
        mkcert -install
