//
// CalorieLine.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** One ingredient line&#39;s part of the estimate. */
public struct CalorieLine: Codable, JSONEncodable, Hashable {

    public static let indexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Scaled calories when counted (zero when negligible). */
    public var calories: CalorieRange?
    public var index: Int
    public var item: String
    /** Display text: \"~120 kcal\", \"Negligible\", \"Not a food\", \"No amount given\", or why it couldn't be counted (\"Not recognized\", \"Amount unclear\"). */
    public var text: String

    public init(calories: CalorieRange? = nil, index: Int, item: String, text: String) {
        self.calories = calories
        self.index = index
        self.item = item
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calories
        case index
        case item
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(calories, forKey: .calories)
        try container.encode(index, forKey: .index)
        try container.encode(item, forKey: .item)
        try container.encode(text, forKey: .text)
    }
}

