//
// CalorieEstimateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CalorieEstimateResponse: Codable, JSONEncodable, Hashable {

    /** Identifies the pinned source data, aliases, and calculation rules. */
    public var databaseVersion: String
    /** Null when no ingredient could be estimated. Otherwise a subtotal that may be partial. */
    public var knownCalories: CalorieRange?
    public var perServingCalories: CalorieRange?
    public var perServingSummary: String?
    public var summary: String
    public var unknownIngredients: [UnknownCalorieIngredient]

    public init(databaseVersion: String, knownCalories: CalorieRange? = nil, perServingCalories: CalorieRange? = nil, perServingSummary: String? = nil, summary: String, unknownIngredients: [UnknownCalorieIngredient]) {
        self.databaseVersion = databaseVersion
        self.knownCalories = knownCalories
        self.perServingCalories = perServingCalories
        self.perServingSummary = perServingSummary
        self.summary = summary
        self.unknownIngredients = unknownIngredients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case databaseVersion = "database_version"
        case knownCalories = "known_calories"
        case perServingCalories = "per_serving_calories"
        case perServingSummary = "per_serving_summary"
        case summary
        case unknownIngredients = "unknown_ingredients"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(databaseVersion, forKey: .databaseVersion)
        try container.encodeIfPresent(knownCalories, forKey: .knownCalories)
        try container.encodeIfPresent(perServingCalories, forKey: .perServingCalories)
        try container.encodeIfPresent(perServingSummary, forKey: .perServingSummary)
        try container.encode(summary, forKey: .summary)
        try container.encode(unknownIngredients, forKey: .unknownIngredients)
    }
}

