//
// CalorieEstimateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Every display string is final; clients render them as-is. */
public struct CalorieEstimateResponse: Codable, JSONEncodable, Hashable {

    /** Identifies the pinned source data, aliases, and calculation rules. */
    public var databaseVersion: String
    /** The main line: \"~520 kcal per serving\", \"At least ~3,100 kcal for the whole recipe\", or \"Not enough ingredient data to estimate calories\". */
    public var headline: String
    /** Null when nothing was counted. A lower bound when status is partial. */
    public var knownCalories: CalorieRange?
    /** The breakdown, one entry per ingredient in order. */
    public var lines: [CalorieLine]
    /** For a partial estimate, the ingredients its lower bound leaves out. */
    public var notCounted: [String]
    public var perServingCalories: CalorieRange?
    /** Some ingredient names are still being recognized in the background; ask again shortly for an estimate that includes them. */
    public var resolving: Bool
    /** Shown under the headline when present. */
    public var secondary: String?
    public var status: CalorieStatus

    public init(databaseVersion: String, headline: String, knownCalories: CalorieRange? = nil, lines: [CalorieLine], notCounted: [String], perServingCalories: CalorieRange? = nil, resolving: Bool, secondary: String? = nil, status: CalorieStatus) {
        self.databaseVersion = databaseVersion
        self.headline = headline
        self.knownCalories = knownCalories
        self.lines = lines
        self.notCounted = notCounted
        self.perServingCalories = perServingCalories
        self.resolving = resolving
        self.secondary = secondary
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case databaseVersion = "database_version"
        case headline
        case knownCalories = "known_calories"
        case lines
        case notCounted = "not_counted"
        case perServingCalories = "per_serving_calories"
        case resolving
        case secondary
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(databaseVersion, forKey: .databaseVersion)
        try container.encode(headline, forKey: .headline)
        try container.encodeIfPresent(knownCalories, forKey: .knownCalories)
        try container.encode(lines, forKey: .lines)
        try container.encode(notCounted, forKey: .notCounted)
        try container.encodeIfPresent(perServingCalories, forKey: .perServingCalories)
        try container.encode(resolving, forKey: .resolving)
        try container.encodeIfPresent(secondary, forKey: .secondary)
        try container.encode(status, forKey: .status)
    }
}

