//
// CalorieStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** How far to trust the estimate, from how many ingredients it couldn&#39;t count. */
public enum CalorieStatus: String, Codable, CaseIterable {
    case complete = "complete"
    case partial = "partial"
    case insufficient = "insufficient"
    case empty = "empty"
}
