//
// CaptureRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CaptureRequest: Codable, JSONEncodable, Hashable {

    /** The HTML content of the page to extract a recipe from */
    public var html: String
    /** The URL the HTML came from (used for source attribution) */
    public var sourceUrl: String

    public init(html: String, sourceUrl: String) {
        self.html = html
        self.sourceUrl = sourceUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case html
        case sourceUrl = "source_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(html, forKey: .html)
        try container.encode(sourceUrl, forKey: .sourceUrl)
    }
}

