//
// CreateMealPlanRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMealPlanRequest: Codable, JSONEncodable, Hashable {

    public var mealDate: Date
    public var mealType: MealType
    public var notes: String?
    public var recipeId: UUID

    public init(mealDate: Date, mealType: MealType, notes: String? = nil, recipeId: UUID) {
        self.mealDate = mealDate
        self.mealType = mealType
        self.notes = notes
        self.recipeId = recipeId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mealDate = "meal_date"
        case mealType = "meal_type"
        case notes
        case recipeId = "recipe_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mealDate, forKey: .mealDate)
        try container.encode(mealType, forKey: .mealType)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(recipeId, forKey: .recipeId)
    }
}

