//
// CreateClientLogRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateClientLogRequest: Codable, JSONEncodable, Hashable {

    public var appVersion: String?
    public var content: String
    public var osInfo: String?
    public var platform: String

    public init(appVersion: String? = nil, content: String, osInfo: String? = nil, platform: String) {
        self.appVersion = appVersion
        self.content = content
        self.osInfo = osInfo
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appVersion = "app_version"
        case content
        case osInfo = "os_info"
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encode(content, forKey: .content)
        try container.encodeIfPresent(osInfo, forKey: .osInfo)
        try container.encode(platform, forKey: .platform)
    }
}

