//
// CreateShoppingListItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateShoppingListItemRequest: Codable, JSONEncodable, Hashable {

    public var amount: String?
    /** Client-generated ID for offline sync */
    public var clientId: UUID?
    public var item: String
    public var note: String?
    public var sourceRecipeId: UUID?
    public var sourceRecipeTitle: String?

    public init(amount: String? = nil, clientId: UUID? = nil, item: String, note: String? = nil, sourceRecipeId: UUID? = nil, sourceRecipeTitle: String? = nil) {
        self.amount = amount
        self.clientId = clientId
        self.item = item
        self.note = note
        self.sourceRecipeId = sourceRecipeId
        self.sourceRecipeTitle = sourceRecipeTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case clientId = "client_id"
        case item
        case note
        case sourceRecipeId = "source_recipe_id"
        case sourceRecipeTitle = "source_recipe_title"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encodeIfPresent(clientId, forKey: .clientId)
        try container.encode(item, forKey: .item)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encodeIfPresent(sourceRecipeId, forKey: .sourceRecipeId)
        try container.encodeIfPresent(sourceRecipeTitle, forKey: .sourceRecipeTitle)
    }
}

