//
// CustomEnrichRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for custom enrichment. */
public struct CustomEnrichRequest: Codable, JSONEncodable, Hashable {

    public var instruction: String
    public var recipe: RecipeContent

    public init(instruction: String, recipe: RecipeContent) {
        self.instruction = instruction
        self.recipe = recipe
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case instruction
        case recipe
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(instruction, forKey: .instruction)
        try container.encode(recipe, forKey: .recipe)
    }
}

