//
// DerivedMeasurement.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Approximate grams for one ingredient line: oz/lb converted, or a volume through the catalog&#39;s density for the food. Computed on every read and never stored, so catalog improvements reach every recipe; never send these back when saving. */
public struct DerivedMeasurement: Codable, JSONEncodable, Hashable {

    public static let ingredientIndexRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var amount: String
    /** Index of the ingredient this belongs to. */
    public var ingredientIndex: Int
    public var unit: String

    public init(amount: String, ingredientIndex: Int, unit: String) {
        self.amount = amount
        self.ingredientIndex = ingredientIndex
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case ingredientIndex = "ingredient_index"
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(ingredientIndex, forKey: .ingredientIndex)
        try container.encode(unit, forKey: .unit)
    }
}

