//
// ErrorCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Machine-readable error code surfaced in every error response.  Clients branch on this instead of parsing the human-readable &#x60;error&#x60; message or guessing from the HTTP status, so changing the wording of a message is never a contract change. Each code maps to exactly one HTTP status (see [&#x60;ErrorCode::status&#x60;]). */
public enum ErrorCode: String, Codable, CaseIterable {
    case notFound = "not_found"
    case invalidRequest = "invalid_request"
    case conflict = "conflict"
    case unauthorized = "unauthorized"
    case forbidden = "forbidden"
    case methodNotAllowed = "method_not_allowed"
    case payloadTooLarge = "payload_too_large"
    case serviceUnavailable = "service_unavailable"
    case _internal = "internal"
}
