//
// EstimateCaloriesRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EstimateCaloriesRequest: Codable, JSONEncodable, Hashable {

    public var ingredients: [Ingredient]
    /** Multiplier applied to the whole recipe, including its serving count. */
    public var scale: Double
    /** Original, unscaled servings text: a count or range, optionally with a \"serves\", \"servings\", \"yield\", or \"makes\" prefix and a \"servings\", \"people\", \"person(s)\", or \"portion(s)\" suffix (\"Serves 4 to 6\", \"Yield: 4\"). A \"makes\" count needs a serving suffix; a yield of something else (\"Makes 12 cookies\", \"Makes 24\") gives no per-serving figure. */
    public var servings: String?

    public init(ingredients: [Ingredient], scale: Double, servings: String? = nil) {
        self.ingredients = ingredients
        self.scale = scale
        self.servings = servings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingredients
        case scale
        case servings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(scale, forKey: .scale)
        try container.encodeIfPresent(servings, forKey: .servings)
    }
}

