//
// GeneratePhotoResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GeneratePhotoResponse: Codable, JSONEncodable, Hashable {

    public var photoId: UUID
    public var versionId: UUID

    public init(photoId: UUID, versionId: UUID) {
        self.photoId = photoId
        self.versionId = versionId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case photoId = "photo_id"
        case versionId = "version_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(photoId, forKey: .photoId)
        try container.encode(versionId, forKey: .versionId)
    }
}

