//
// GenerateDescriptionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateDescriptionResponse: Codable, JSONEncodable, Hashable {

    public var cached: Bool
    public var changed: Bool
    public var generatedDescription: String
    public var originalDescription: String?

    public init(cached: Bool, changed: Bool, generatedDescription: String, originalDescription: String? = nil) {
        self.cached = cached
        self.changed = changed
        self.generatedDescription = generatedDescription
        self.originalDescription = originalDescription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cached
        case changed
        case generatedDescription = "generated_description"
        case originalDescription = "original_description"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cached, forKey: .cached)
        try container.encode(changed, forKey: .changed)
        try container.encode(generatedDescription, forKey: .generatedDescription)
        try container.encodeIfPresent(originalDescription, forKey: .originalDescription)
    }
}

