//
// GetClientLogResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetClientLogResponse: Codable, JSONEncodable, Hashable {

    public var appVersion: String?
    public var content: String
    public var createdAt: Date
    public var id: UUID
    public var osInfo: String?
    public var platform: String

    public init(appVersion: String? = nil, content: String, createdAt: Date, id: UUID, osInfo: String? = nil, platform: String) {
        self.appVersion = appVersion
        self.content = content
        self.createdAt = createdAt
        self.id = id
        self.osInfo = osInfo
        self.platform = platform
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appVersion = "app_version"
        case content
        case createdAt = "created_at"
        case id
        case osInfo = "os_info"
        case platform
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(appVersion, forKey: .appVersion)
        try container.encode(content, forKey: .content)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(osInfo, forKey: .osInfo)
        try container.encode(platform, forKey: .platform)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension GetClientLogResponse: Identifiable {}
