//
// ImportRawRecipe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Raw recipe data for import (mirrors ramekin_core::RawRecipe) */
public struct ImportRawRecipe: Codable, JSONEncodable, Hashable {

    public var categories: [String]?
    public var cookTime: String?
    public var description: String?
    public var difficulty: String?
    /** Image URLs found in the recipe (not used for imports with pre-uploaded photos) */
    public var imageUrls: [String]?
    /** Ingredients as a newline-separated blob */
    public var ingredients: String
    /** Instructions as a blob (could be HTML or plain text) */
    public var instructions: String
    public var notes: String?
    public var nutritionalInfo: String?
    public var prepTime: String?
    public var rating: Int?
    public var servings: String?
    public var sourceName: String?
    /** Source URL (optional for imports without a web source) */
    public var sourceUrl: String?
    public var title: String
    public var totalTime: String?

    public init(categories: [String]? = nil, cookTime: String? = nil, description: String? = nil, difficulty: String? = nil, imageUrls: [String]? = nil, ingredients: String, instructions: String, notes: String? = nil, nutritionalInfo: String? = nil, prepTime: String? = nil, rating: Int? = nil, servings: String? = nil, sourceName: String? = nil, sourceUrl: String? = nil, title: String, totalTime: String? = nil) {
        self.categories = categories
        self.cookTime = cookTime
        self.description = description
        self.difficulty = difficulty
        self.imageUrls = imageUrls
        self.ingredients = ingredients
        self.instructions = instructions
        self.notes = notes
        self.nutritionalInfo = nutritionalInfo
        self.prepTime = prepTime
        self.rating = rating
        self.servings = servings
        self.sourceName = sourceName
        self.sourceUrl = sourceUrl
        self.title = title
        self.totalTime = totalTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categories
        case cookTime = "cook_time"
        case description
        case difficulty
        case imageUrls = "image_urls"
        case ingredients
        case instructions
        case notes
        case nutritionalInfo = "nutritional_info"
        case prepTime = "prep_time"
        case rating
        case servings
        case sourceName = "source_name"
        case sourceUrl = "source_url"
        case title
        case totalTime = "total_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(categories, forKey: .categories)
        try container.encodeIfPresent(cookTime, forKey: .cookTime)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(difficulty, forKey: .difficulty)
        try container.encodeIfPresent(imageUrls, forKey: .imageUrls)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(instructions, forKey: .instructions)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(nutritionalInfo, forKey: .nutritionalInfo)
        try container.encodeIfPresent(prepTime, forKey: .prepTime)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(servings, forKey: .servings)
        try container.encodeIfPresent(sourceName, forKey: .sourceName)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(totalTime, forKey: .totalTime)
    }
}

