//
// ImportExtractionMethod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Extraction method for imported recipes (mirrors ramekin_core::ExtractionMethod) */
public enum ImportExtractionMethod: String, Codable, CaseIterable {
    case jsonLd = "json_ld"
    case microdata = "microdata"
    case paprika = "paprika"
}
