//
// ImportFromPhotosResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImportFromPhotosResponse: Codable, JSONEncodable, Hashable {

    /** The created job ID */
    public var jobId: UUID
    /** Current job status */
    public var status: String

    public init(jobId: UUID, status: String) {
        self.jobId = jobId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobId = "job_id"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(status, forKey: .status)
    }
}

