//
// IngredientWeightsStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Weights the catalog lacks for foods in the user&#39;s recipes (a density, or a counted unit such as \&quot;bunch\&quot;), estimated in the background: every estimate for those foods, whichever view queued it. */
public struct IngredientWeightsStatus: Codable, JSONEncodable, Hashable {

    /** Estimated; lines using one say \"estimated weight\". */
    public var estimated: Int64
    /** The last attempt failed; retry to try again. */
    public var failed: Int64
    /** The most recent failures. */
    public var failures: [IngredientWeightFailure]
    /** The model said there's no typical weight; still unknown in estimates. */
    public var noTypicalWeight: Int64
    /** Waiting for the background estimator (queued when an estimate is shown). */
    public var pending: Int64

    public init(estimated: Int64, failed: Int64, failures: [IngredientWeightFailure], noTypicalWeight: Int64, pending: Int64) {
        self.estimated = estimated
        self.failed = failed
        self.failures = failures
        self.noTypicalWeight = noTypicalWeight
        self.pending = pending
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case estimated
        case failed
        case failures
        case noTypicalWeight = "no_typical_weight"
        case pending
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(estimated, forKey: .estimated)
        try container.encode(failed, forKey: .failed)
        try container.encode(failures, forKey: .failures)
        try container.encode(noTypicalWeight, forKey: .noTypicalWeight)
        try container.encode(pending, forKey: .pending)
    }
}

