//
// IngredientNamesQueuedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IngredientNamesQueuedResponse: Codable, JSONEncodable, Hashable {

    public static let queuedRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Names and weights queued again by this call. */
    public var queued: Int

    public init(queued: Int) {
        self.queued = queued
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case queued
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(queued, forKey: .queued)
    }
}

