//
// IngredientNameFailure.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IngredientNameFailure: Codable, JSONEncodable, Hashable {

    public var attempts: Int
    public var error: String
    public var name: String

    public init(attempts: Int, error: String, name: String) {
        self.attempts = attempts
        self.error = error
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attempts
        case error
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(attempts, forKey: .attempts)
        try container.encode(error, forKey: .error)
        try container.encode(name, forKey: .name)
    }
}

