//
// ListRecipesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ListRecipesResponse: Codable, JSONEncodable, Hashable {

    public var pagination: PaginationMetadata
    public var recipes: [RecipeSummary]

    public init(pagination: PaginationMetadata, recipes: [RecipeSummary]) {
        self.pagination = pagination
        self.recipes = recipes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pagination
        case recipes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pagination, forKey: .pagination)
        try container.encode(recipes, forKey: .recipes)
    }
}

