//
// LookupImportJobsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request body for looking up import jobs by idempotency key */
public struct LookupImportJobsRequest: Codable, JSONEncodable, Hashable {

    /** Keys previously sent as ImportRecipeRequest.idempotency_key (at most 1000) */
    public var idempotencyKeys: [String]

    public init(idempotencyKeys: [String]) {
        self.idempotencyKeys = idempotencyKeys
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case idempotencyKeys = "idempotency_keys"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(idempotencyKeys, forKey: .idempotencyKeys)
    }
}

