//
// LookupImportJobsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The caller&#39;s import jobs for the requested keys; unknown keys are omitted */
public struct LookupImportJobsResponse: Codable, JSONEncodable, Hashable {

    public var jobs: [ImportJobKey]

    public init(jobs: [ImportJobKey]) {
        self.jobs = jobs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobs, forKey: .jobs)
    }
}

