//
// MealPlanListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MealPlanListResponse: Codable, JSONEncodable, Hashable {

    public var mealPlans: [MealPlanItem]

    public init(mealPlans: [MealPlanItem]) {
        self.mealPlans = mealPlans
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mealPlans = "meal_plans"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mealPlans, forKey: .mealPlans)
    }
}

