//
// MealPlanItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MealPlanItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var mealDate: Date
    public var mealType: MealType
    public var notes: String?
    public var recipeId: UUID
    public var recipeTitle: String
    public var thumbnailPhotoId: UUID?

    public init(id: UUID, mealDate: Date, mealType: MealType, notes: String? = nil, recipeId: UUID, recipeTitle: String, thumbnailPhotoId: UUID? = nil) {
        self.id = id
        self.mealDate = mealDate
        self.mealType = mealType
        self.notes = notes
        self.recipeId = recipeId
        self.recipeTitle = recipeTitle
        self.thumbnailPhotoId = thumbnailPhotoId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case mealDate = "meal_date"
        case mealType = "meal_type"
        case notes
        case recipeId = "recipe_id"
        case recipeTitle = "recipe_title"
        case thumbnailPhotoId = "thumbnail_photo_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(mealDate, forKey: .mealDate)
        try container.encode(mealType, forKey: .mealType)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(recipeId, forKey: .recipeId)
        try container.encode(recipeTitle, forKey: .recipeTitle)
        try container.encodeIfPresent(thumbnailPhotoId, forKey: .thumbnailPhotoId)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MealPlanItem: Identifiable {}
