//
// NormalizeTitleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NormalizeTitleResponse: Codable, JSONEncodable, Hashable {

    public var cached: Bool
    public var changed: Bool
    public var normalizedTitle: String
    public var originalTitle: String

    public init(cached: Bool, changed: Bool, normalizedTitle: String, originalTitle: String) {
        self.cached = cached
        self.changed = changed
        self.normalizedTitle = normalizedTitle
        self.originalTitle = originalTitle
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cached
        case changed
        case normalizedTitle = "normalized_title"
        case originalTitle = "original_title"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cached, forKey: .cached)
        try container.encode(changed, forKey: .changed)
        try container.encode(normalizedTitle, forKey: .normalizedTitle)
        try container.encode(originalTitle, forKey: .originalTitle)
    }
}

