//
// PaginationMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaginationMetadata: Codable, JSONEncodable, Hashable {

    /** Number of items requested (limit) */
    public var limit: Int64
    /** Number of items skipped (offset) */
    public var offset: Int64
    /** Total number of items available */
    public var total: Int64

    public init(limit: Int64, offset: Int64, total: Int64) {
        self.limit = limit
        self.offset = offset
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case offset
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(limit, forKey: .limit)
        try container.encode(offset, forKey: .offset)
        try container.encode(total, forKey: .total)
    }
}

