//
// RecipeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RecipeResponse: Codable, JSONEncodable, Hashable {

    public var cookTime: String?
    public var createdAt: Date
    public var description: String?
    public var difficulty: String?
    public var id: UUID
    public var ingredients: [Ingredient]
    public var instructions: String
    public var notes: String?
    public var nutritionalInfo: String?
    public var photoIds: [UUID]
    public var prepTime: String?
    public var rating: Int?
    public var servings: String?
    public var sourceName: String?
    public var sourceUrl: String?
    public var tags: [String]
    public var title: String
    public var totalTime: String?
    /** When viewing a specific version, this is the version's created_at */
    public var updatedAt: Date
    /** Version metadata */
    public var versionId: UUID
    public var versionSource: String

    public init(cookTime: String? = nil, createdAt: Date, description: String? = nil, difficulty: String? = nil, id: UUID, ingredients: [Ingredient], instructions: String, notes: String? = nil, nutritionalInfo: String? = nil, photoIds: [UUID], prepTime: String? = nil, rating: Int? = nil, servings: String? = nil, sourceName: String? = nil, sourceUrl: String? = nil, tags: [String], title: String, totalTime: String? = nil, updatedAt: Date, versionId: UUID, versionSource: String) {
        self.cookTime = cookTime
        self.createdAt = createdAt
        self.description = description
        self.difficulty = difficulty
        self.id = id
        self.ingredients = ingredients
        self.instructions = instructions
        self.notes = notes
        self.nutritionalInfo = nutritionalInfo
        self.photoIds = photoIds
        self.prepTime = prepTime
        self.rating = rating
        self.servings = servings
        self.sourceName = sourceName
        self.sourceUrl = sourceUrl
        self.tags = tags
        self.title = title
        self.totalTime = totalTime
        self.updatedAt = updatedAt
        self.versionId = versionId
        self.versionSource = versionSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cookTime = "cook_time"
        case createdAt = "created_at"
        case description
        case difficulty
        case id
        case ingredients
        case instructions
        case notes
        case nutritionalInfo = "nutritional_info"
        case photoIds = "photo_ids"
        case prepTime = "prep_time"
        case rating
        case servings
        case sourceName = "source_name"
        case sourceUrl = "source_url"
        case tags
        case title
        case totalTime = "total_time"
        case updatedAt = "updated_at"
        case versionId = "version_id"
        case versionSource = "version_source"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cookTime, forKey: .cookTime)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(difficulty, forKey: .difficulty)
        try container.encode(id, forKey: .id)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(instructions, forKey: .instructions)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(nutritionalInfo, forKey: .nutritionalInfo)
        try container.encode(photoIds, forKey: .photoIds)
        try container.encodeIfPresent(prepTime, forKey: .prepTime)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(servings, forKey: .servings)
        try container.encodeIfPresent(sourceName, forKey: .sourceName)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encode(tags, forKey: .tags)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(totalTime, forKey: .totalTime)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(versionId, forKey: .versionId)
        try container.encode(versionSource, forKey: .versionSource)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RecipeResponse: Identifiable {}
