//
// ReparseIngredientsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReparseIngredientsResponse: Codable, JSONEncodable, Hashable {

    public static let ingredientsChangedRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let recipesCheckedRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let recipesUpdatedRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    /** Ingredient lines whose item changed. */
    public var ingredientsChanged: Int
    /** Recipes whose current version was checked. */
    public var recipesChecked: Int
    /** Recipes that got a new version because an ingredient changed. */
    public var recipesUpdated: Int

    public init(ingredientsChanged: Int, recipesChecked: Int, recipesUpdated: Int) {
        self.ingredientsChanged = ingredientsChanged
        self.recipesChecked = recipesChecked
        self.recipesUpdated = recipesUpdated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingredientsChanged = "ingredients_changed"
        case recipesChecked = "recipes_checked"
        case recipesUpdated = "recipes_updated"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ingredientsChanged, forKey: .ingredientsChanged)
        try container.encode(recipesChecked, forKey: .recipesChecked)
        try container.encode(recipesUpdated, forKey: .recipesUpdated)
    }
}

