//
// RetryScrapeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RetryScrapeResponse: Codable, JSONEncodable, Hashable {

    /** The scrape job ID */
    public var id: UUID
    /** New job status after retry */
    public var status: String

    public init(id: UUID, status: String) {
        self.id = id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension RetryScrapeResponse: Identifiable {}
