//
// ScrapeJobResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ScrapeJobResponse: Codable, JSONEncodable, Hashable {

    /** Whether this job can be retried */
    public var canRetry: Bool
    /** Error message if failed */
    public var error: String?
    /** Which step failed (for retry logic) */
    public var failedAtStep: String?
    /** The scrape job ID */
    public var id: UUID
    /** Recipe ID if completed successfully */
    public var recipeId: UUID?
    /** Number of retry attempts */
    public var retryCount: Int
    /** Current job status (pending, scraping, parsing, completed, failed) */
    public var status: String
    /** URL being scraped (optional for imports) */
    public var url: String?

    public init(canRetry: Bool, error: String? = nil, failedAtStep: String? = nil, id: UUID, recipeId: UUID? = nil, retryCount: Int, status: String, url: String? = nil) {
        self.canRetry = canRetry
        self.error = error
        self.failedAtStep = failedAtStep
        self.id = id
        self.recipeId = recipeId
        self.retryCount = retryCount
        self.status = status
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canRetry = "can_retry"
        case error
        case failedAtStep = "failed_at_step"
        case id
        case recipeId = "recipe_id"
        case retryCount = "retry_count"
        case status
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(canRetry, forKey: .canRetry)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(failedAtStep, forKey: .failedAtStep)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(recipeId, forKey: .recipeId)
        try container.encode(retryCount, forKey: .retryCount)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(url, forKey: .url)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ScrapeJobResponse: Identifiable {}
