//
// SignupResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SignupResponse: Codable, JSONEncodable, Hashable {

    public var token: String
    public var userId: UUID

    public init(token: String, userId: UUID) {
        self.token = token
        self.userId = userId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case userId = "user_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(userId, forKey: .userId)
    }
}

