//
// SortBy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Sort field for recipe list */
public enum SortBy: String, Codable, CaseIterable {
    case updatedAt = "updated_at"
    case random = "random"
}
