//
// StepState.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A single pipeline step&#39;s state for the status API response. */
public struct StepState: Codable, JSONEncodable, Hashable {

    public var durationMs: Int64?
    public var error: String?
    public var finishedAt: Date?
    public var hasOutput: Bool
    public var name: String
    public var startedAt: Date?
    /** One of \"pending\", \"running\", \"completed\", \"failed\", \"skipped\". */
    public var status: String
    public var summary: String?

    public init(durationMs: Int64? = nil, error: String? = nil, finishedAt: Date? = nil, hasOutput: Bool, name: String, startedAt: Date? = nil, status: String, summary: String? = nil) {
        self.durationMs = durationMs
        self.error = error
        self.finishedAt = finishedAt
        self.hasOutput = hasOutput
        self.name = name
        self.startedAt = startedAt
        self.status = status
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case durationMs = "duration_ms"
        case error
        case finishedAt = "finished_at"
        case hasOutput = "has_output"
        case name
        case startedAt = "started_at"
        case status
        case summary
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(durationMs, forKey: .durationMs)
        try container.encodeIfPresent(error, forKey: .error)
        try container.encodeIfPresent(finishedAt, forKey: .finishedAt)
        try container.encode(hasOutput, forKey: .hasOutput)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

