//
// SyncRecipe.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Read-only recipe data needed to populate the iOS cache and mirror server search. */
public struct SyncRecipe: Codable, JSONEncodable, Hashable {

    public var createdAt: Date
    public var description: String?
    public var id: UUID
    public var ingredients: [Ingredient]
    public var instructions: String
    public var notes: String?
    public var rating: Int?
    public var tags: [String]
    public var thumbnailPhotoId: UUID?
    public var title: String
    public var updatedAt: Date

    public init(createdAt: Date, description: String? = nil, id: UUID, ingredients: [Ingredient], instructions: String, notes: String? = nil, rating: Int? = nil, tags: [String], thumbnailPhotoId: UUID? = nil, title: String, updatedAt: Date) {
        self.createdAt = createdAt
        self.description = description
        self.id = id
        self.ingredients = ingredients
        self.instructions = instructions
        self.notes = notes
        self.rating = rating
        self.tags = tags
        self.thumbnailPhotoId = thumbnailPhotoId
        self.title = title
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case description
        case id
        case ingredients
        case instructions
        case notes
        case rating
        case tags
        case thumbnailPhotoId = "thumbnail_photo_id"
        case title
        case updatedAt = "updated_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(id, forKey: .id)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(instructions, forKey: .instructions)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encode(tags, forKey: .tags)
        try container.encodeIfPresent(thumbnailPhotoId, forKey: .thumbnailPhotoId)
        try container.encode(title, forKey: .title)
        try container.encode(updatedAt, forKey: .updatedAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SyncRecipe: Identifiable {}
