//
// SyncCreatedItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncCreatedItem: Codable, JSONEncodable, Hashable {

    public var clientId: UUID
    public var serverId: UUID
    public var version: Int

    public init(clientId: UUID, serverId: UUID, version: Int) {
        self.clientId = clientId
        self.serverId = serverId
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clientId = "client_id"
        case serverId = "server_id"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(clientId, forKey: .clientId)
        try container.encode(serverId, forKey: .serverId)
        try container.encode(version, forKey: .version)
    }
}

