//
// SyncRecipesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncRecipesResponse: Codable, JSONEncodable, Hashable {

    /** Opaque cursor to pass to the next sync. Changes may be redelivered across syncs, but none can be skipped. */
    public var cursor: Int64
    /** Recipe IDs deleted at or after `cursor`. */
    public var deleted: [UUID]
    /** Active recipes changed at or after `cursor`. All active recipes are returned when `cursor` is absent. */
    public var recipes: [SyncRecipe]

    public init(cursor: Int64, deleted: [UUID], recipes: [SyncRecipe]) {
        self.cursor = cursor
        self.deleted = deleted
        self.recipes = recipes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cursor
        case deleted
        case recipes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cursor, forKey: .cursor)
        try container.encode(deleted, forKey: .deleted)
        try container.encode(recipes, forKey: .recipes)
    }
}

