//
// SyncResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncResponse: Codable, JSONEncodable, Hashable {

    /** Canonical category display order for grouping items; every item's `category` is guaranteed to appear in this list. */
    public var categoryOrder: [String]
    /** Items that were created (maps client_id to server_id) */
    public var created: [SyncCreatedItem]
    /** IDs of items that were deleted */
    public var deleted: [UUID]
    /** Server-side changes since last_sync_at */
    public var serverChanges: [SyncServerChange]
    /** New sync timestamp to use for next sync */
    public var syncTimestamp: Date
    /** Items that were updated (with success status) */
    public var updated: [SyncUpdatedItem]

    public init(categoryOrder: [String], created: [SyncCreatedItem], deleted: [UUID], serverChanges: [SyncServerChange], syncTimestamp: Date, updated: [SyncUpdatedItem]) {
        self.categoryOrder = categoryOrder
        self.created = created
        self.deleted = deleted
        self.serverChanges = serverChanges
        self.syncTimestamp = syncTimestamp
        self.updated = updated
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case categoryOrder = "category_order"
        case created
        case deleted
        case serverChanges = "server_changes"
        case syncTimestamp = "sync_timestamp"
        case updated
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(categoryOrder, forKey: .categoryOrder)
        try container.encode(created, forKey: .created)
        try container.encode(deleted, forKey: .deleted)
        try container.encode(serverChanges, forKey: .serverChanges)
        try container.encode(syncTimestamp, forKey: .syncTimestamp)
        try container.encode(updated, forKey: .updated)
    }
}

