//
// SyncUpdatedItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncUpdatedItem: Codable, JSONEncodable, Hashable {

    public var id: UUID
    public var success: Bool
    public var version: Int

    public init(id: UUID, success: Bool, version: Int) {
        self.id = id
        self.success = success
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case success
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(success, forKey: .success)
        try container.encode(version, forKey: .version)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SyncUpdatedItem: Identifiable {}
