//
// SyncServerChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncServerChange: Codable, JSONEncodable, Hashable {

    public var amount: String?
    /** Aisle category for grouping (override when set, otherwise computed). */
    public var category: String
    /** User-selected category override; when set, it wins over computed category. */
    public var categoryOverride: String?
    /** Category computed from the item name before applying any override. */
    public var computedCategory: String
    public var id: UUID
    public var isChecked: Bool
    public var item: String
    public var note: String?
    public var sortOrder: Int
    public var sourceRecipeId: UUID?
    public var sourceRecipeTitle: String?
    public var updatedAt: Date
    public var version: Int

    public init(amount: String? = nil, category: String, categoryOverride: String? = nil, computedCategory: String, id: UUID, isChecked: Bool, item: String, note: String? = nil, sortOrder: Int, sourceRecipeId: UUID? = nil, sourceRecipeTitle: String? = nil, updatedAt: Date, version: Int) {
        self.amount = amount
        self.category = category
        self.categoryOverride = categoryOverride
        self.computedCategory = computedCategory
        self.id = id
        self.isChecked = isChecked
        self.item = item
        self.note = note
        self.sortOrder = sortOrder
        self.sourceRecipeId = sourceRecipeId
        self.sourceRecipeTitle = sourceRecipeTitle
        self.updatedAt = updatedAt
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case category
        case categoryOverride = "category_override"
        case computedCategory = "computed_category"
        case id
        case isChecked = "is_checked"
        case item
        case note
        case sortOrder = "sort_order"
        case sourceRecipeId = "source_recipe_id"
        case sourceRecipeTitle = "source_recipe_title"
        case updatedAt = "updated_at"
        case version
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(amount, forKey: .amount)
        try container.encode(category, forKey: .category)
        try container.encodeIfPresent(categoryOverride, forKey: .categoryOverride)
        try container.encode(computedCategory, forKey: .computedCategory)
        try container.encode(id, forKey: .id)
        try container.encode(isChecked, forKey: .isChecked)
        try container.encode(item, forKey: .item)
        try container.encodeIfPresent(note, forKey: .note)
        try container.encode(sortOrder, forKey: .sortOrder)
        try container.encodeIfPresent(sourceRecipeId, forKey: .sourceRecipeId)
        try container.encodeIfPresent(sourceRecipeTitle, forKey: .sourceRecipeTitle)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(version, forKey: .version)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension SyncServerChange: Identifiable {}
