//
// SyncRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncRequest: Codable, JSONEncodable, Hashable {

    /** Items created offline */
    public var creates: [SyncCreateItem]?
    /** IDs of items deleted offline */
    public var deletes: [UUID]?
    /** Last sync timestamp - server will return changes since this time */
    public var lastSyncAt: Date?
    /** Items updated offline */
    public var updates: [SyncUpdateItem]?

    public init(creates: [SyncCreateItem]? = nil, deletes: [UUID]? = nil, lastSyncAt: Date? = nil, updates: [SyncUpdateItem]? = nil) {
        self.creates = creates
        self.deletes = deletes
        self.lastSyncAt = lastSyncAt
        self.updates = updates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case creates
        case deletes
        case lastSyncAt = "last_sync_at"
        case updates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(creates, forKey: .creates)
        try container.encodeIfPresent(deletes, forKey: .deletes)
        try container.encodeIfPresent(lastSyncAt, forKey: .lastSyncAt)
        try container.encodeIfPresent(updates, forKey: .updates)
    }
}

