//
// TagItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TagItem: Codable, JSONEncodable, Hashable {

    public var createdAt: Date
    public var id: UUID
    public var name: String
    /** Number of recipes using this tag */
    public var recipeCount: Int64

    public init(createdAt: Date, id: UUID, name: String, recipeCount: Int64) {
        self.createdAt = createdAt
        self.id = id
        self.name = name
        self.recipeCount = recipeCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case id
        case name
        case recipeCount = "recipe_count"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(recipeCount, forKey: .recipeCount)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension TagItem: Identifiable {}
