//
// TagsListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TagsListResponse: Codable, JSONEncodable, Hashable {

    public var tags: [TagItem]

    public init(tags: [TagItem]) {
        self.tags = tags
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tags
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(tags, forKey: .tags)
    }
}

