//
// UpdateMealPlanRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateMealPlanRequest: Codable, JSONEncodable, Hashable {

    public var mealDate: Date?
    public var mealType: MealType?
    /** Set to empty string to clear notes, or provide new value */
    public var notes: String?

    public init(mealDate: Date? = nil, mealType: MealType? = nil, notes: String? = nil) {
        self.mealDate = mealDate
        self.mealType = mealType
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mealDate = "meal_date"
        case mealType = "meal_type"
        case notes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(mealDate, forKey: .mealDate)
        try container.encodeIfPresent(mealType, forKey: .mealType)
        try container.encodeIfPresent(notes, forKey: .notes)
    }
}

