//
// UpdateRecipeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateRecipeRequest: Codable, JSONEncodable, Hashable {

    public var cookTime: String?
    public var description: String?
    public var difficulty: String?
    public var ingredients: [Ingredient]?
    public var instructions: String?
    public var notes: String?
    public var nutritionalInfo: String?
    public var photoIds: [UUID]?
    public var prepTime: String?
    public var rating: Int?
    public var servings: String?
    public var sourceName: String?
    public var sourceUrl: String?
    public var tags: [String]?
    public var title: String?
    public var totalTime: String?

    public init(cookTime: String? = nil, description: String? = nil, difficulty: String? = nil, ingredients: [Ingredient]? = nil, instructions: String? = nil, notes: String? = nil, nutritionalInfo: String? = nil, photoIds: [UUID]? = nil, prepTime: String? = nil, rating: Int? = nil, servings: String? = nil, sourceName: String? = nil, sourceUrl: String? = nil, tags: [String]? = nil, title: String? = nil, totalTime: String? = nil) {
        self.cookTime = cookTime
        self.description = description
        self.difficulty = difficulty
        self.ingredients = ingredients
        self.instructions = instructions
        self.notes = notes
        self.nutritionalInfo = nutritionalInfo
        self.photoIds = photoIds
        self.prepTime = prepTime
        self.rating = rating
        self.servings = servings
        self.sourceName = sourceName
        self.sourceUrl = sourceUrl
        self.tags = tags
        self.title = title
        self.totalTime = totalTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cookTime = "cook_time"
        case description
        case difficulty
        case ingredients
        case instructions
        case notes
        case nutritionalInfo = "nutritional_info"
        case photoIds = "photo_ids"
        case prepTime = "prep_time"
        case rating
        case servings
        case sourceName = "source_name"
        case sourceUrl = "source_url"
        case tags
        case title
        case totalTime = "total_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cookTime, forKey: .cookTime)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(difficulty, forKey: .difficulty)
        try container.encodeIfPresent(ingredients, forKey: .ingredients)
        try container.encodeIfPresent(instructions, forKey: .instructions)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(nutritionalInfo, forKey: .nutritionalInfo)
        try container.encodeIfPresent(photoIds, forKey: .photoIds)
        try container.encodeIfPresent(prepTime, forKey: .prepTime)
        try container.encodeIfPresent(rating, forKey: .rating)
        try container.encodeIfPresent(servings, forKey: .servings)
        try container.encodeIfPresent(sourceName, forKey: .sourceName)
        try container.encodeIfPresent(sourceUrl, forKey: .sourceUrl)
        try container.encodeIfPresent(tags, forKey: .tags)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(totalTime, forKey: .totalTime)
    }
}

