//
// VersionSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Version summary for listing version history */
public struct VersionSummary: Codable, JSONEncodable, Hashable {

    public var createdAt: Date
    public var id: UUID
    public var isCurrent: Bool
    public var title: String
    public var versionSource: String

    public init(createdAt: Date, id: UUID, isCurrent: Bool, title: String, versionSource: String) {
        self.createdAt = createdAt
        self.id = id
        self.isCurrent = isCurrent
        self.title = title
        self.versionSource = versionSource
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt = "created_at"
        case id
        case isCurrent = "is_current"
        case title
        case versionSource = "version_source"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(isCurrent, forKey: .isCurrent)
        try container.encode(title, forKey: .title)
        try container.encode(versionSource, forKey: .versionSource)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension VersionSummary: Identifiable {}
