version: "0.5"

log_location: ./logs/dev.log
log_configuration:
  disable_json: true
  no_color: true
  add_timestamp: true
  flush_each_line: true

processes:
  server:
    command: ${SERVER_CMD:-cargo watch -x run}
    working_dir: ./server
    availability:
      restart: ${SERVER_RESTART:-on_failure}
    readiness_probe:
      http_get:
        host: localhost
        port: ${PORT}
        path: /api/test/unauthed-ping

  ui:
    command: npm run dev
    working_dir: ./ramekin-ui

  seed:
    command: cargo run -q -- seed --username t --password t ../data/dev/seed.paprikarecipes
    working_dir: ./cli
    depends_on:
      server:
        condition: process_healthy
    availability:
      restart: "no"

  screenshot:
    command: cargo run -q -- screenshot --output-dir ../logs
    working_dir: ./cli
    depends_on:
      seed:
        condition: process_completed_successfully
      ui:
        condition: process_started
    availability:
      restart: "no"
      exit_on_end: ${PC_EXIT_ON_END:-false}
