version: "0.5"
extends: compose/base.yaml

log_location: ./logs/dev.log

processes:
  server:
    command: ${SERVER_CMD:-cargo watch -x run}
    working_dir: ./server
    availability:
      restart: ${SERVER_RESTART:-on_failure}

  certs:
    command: ./scripts/setup-certs.sh
    availability:
      restart: "no"

  ui:
    command: npm install && npm run dev
    working_dir: ./ramekin-ui
    depends_on:
      certs:
        condition: process_completed_successfully

  seed:
    command: >-
      cargo run -q -- seed --server-url http://localhost:${PORT}
      --username t --password t ../data/dev/seed.paprikarecipes
    working_dir: ./cli
    depends_on:
      server:
        condition: process_healthy
    availability:
      restart: "no"

  ready:
    command: echo "UI ready at https://localhost:${UI_PORT}"
    depends_on:
      screenshot:
        condition: process_completed_successfully
    availability:
      restart: "no"

  screenshot:
    command: cargo run -q -- screenshot --ui-url https://localhost:${UI_PORT} --output-dir ../logs
    working_dir: ./cli
    depends_on:
      seed:
        condition: process_completed_successfully
      ui:
        condition: process_started
    availability:
      restart: "no"
      exit_on_end: ${PC_EXIT_ON_END:-false}
