version: "0.5"
extends: compose/base.yaml

log_location: ./logs/test-ui.log

processes:
  mock-openrouter:
    command: python3 tests/mock_openrouter.py ${MOCK_OPENROUTER_PORT}
    readiness_probe:
      http_get:
        host: localhost
        port: ${MOCK_OPENROUTER_PORT}
        path: /

  server:
    working_dir: ./server
    environment:
      - OPENROUTER_API_KEY=test-api-key
      - RAMEKIN_AI_BASE_URL=http://localhost:${MOCK_OPENROUTER_PORT}/v1
    depends_on:
      mock-openrouter:
        condition: process_healthy

  ui:
    command: npm run dev -- --port ${UI_PORT} --strictPort
    working_dir: ./ramekin-ui
    environment:
      - PORT=${PORT}
    readiness_probe:
      http_get:
        host: localhost
        port: ${UI_PORT}
        path: /
    depends_on:
      server:
        condition: process_healthy

  seed:
    command: |
      echo "[TIMING] seed starting at $(date +%H:%M:%S)"
      START=$(date +%s)
      cargo run -q -- seed --server-url http://localhost:${PORT} --username t --password t ../data/dev/seed.paprikarecipes
      echo "[TIMING] seed completed in $(($(date +%s) - START))s"
    working_dir: ./cli
    availability:
      restart: "no"
    depends_on:
      server:
        condition: process_healthy

  ui-tests:
    command: |
      echo "[TIMING] ui-tests starting at $(date +%H:%M:%S)"
      START=$(date +%s)
      pytest tests/ui -v
      EXIT_CODE=$?
      echo "[TIMING] ui-tests completed in $(($(date +%s) - START))s"
      exit $EXIT_CODE
    environment:
      - API_BASE_URL=http://localhost:${PORT}
      - UI_BASE_URL=http://localhost:${UI_PORT}
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      seed:
        condition: process_completed_successfully
      ui:
        condition: process_healthy
