version: "0.5"
extends: compose/base.yaml

log_location: ./logs/test.log

processes:
  rust-tests-server:
    command: |
      echo "[TIMING] rust-tests-server starting at $(date +%H:%M:%S)"
      START=$(date +%s)
      cargo test -q --manifest-path server/Cargo.toml
      echo "[TIMING] rust-tests-server completed in $(($(date +%s) - START))s"
    availability:
      restart: "no"

  rust-tests-cli:
    command: |
      echo "[TIMING] rust-tests-cli starting at $(date +%H:%M:%S)"
      START=$(date +%s)
      cargo test -q --manifest-path cli/Cargo.toml
      echo "[TIMING] rust-tests-cli completed in $(($(date +%s) - START))s"
    availability:
      restart: "no"

  rust-tests-core:
    command: |
      echo "[TIMING] rust-tests-core starting at $(date +%H:%M:%S)"
      START=$(date +%s)
      cargo test -q --manifest-path ramekin-core/Cargo.toml
      echo "[TIMING] rust-tests-core completed in $(($(date +%s) - START))s"
    availability:
      restart: "no"

  fixture:
    command: python3 ../fixture_server.py ${FIXTURE_PORT}
    working_dir: ./tests/scrape_fixtures
    readiness_probe:
      http_get:
        host: localhost
        port: ${FIXTURE_PORT}
        path: /

  mock-openrouter:
    command: python3 tests/mock_openrouter.py ${MOCK_OPENROUTER_PORT}
    readiness_probe:
      http_get:
        host: localhost
        port: ${MOCK_OPENROUTER_PORT}
        path: /

  server:
    working_dir: ./server
    environment:
      - SCRAPE_ALLOWED_HOSTS=localhost:${FIXTURE_PORT}
      - OPENROUTER_API_KEY=test-api-key
      - RAMEKIN_AI_BASE_URL=http://localhost:${MOCK_OPENROUTER_PORT}/v1
    depends_on:
      fixture:
        condition: process_healthy
      mock-openrouter:
        condition: process_healthy

  api-tests:
    command: |
      echo "[TIMING] api-tests starting at $(date +%H:%M:%S)"
      START=$(date +%s)
      pytest tests -v -n auto --ignore=tests/ui
      EXIT_CODE=$?
      echo "[TIMING] api-tests completed in $(($(date +%s) - START))s"
      exit $EXIT_CODE
    environment:
      - FIXTURE_BASE_URL=http://localhost:${FIXTURE_PORT}
      - API_BASE_URL=http://localhost:${PORT}
      - CLI_PATH=./cli/target/debug/ramekin-cli
    availability:
      restart: "no"
    depends_on:
      server:
        condition: process_healthy

  all-tests:
    command: echo "All tests completed successfully"
    availability:
      restart: "no"
      exit_on_end: true
    depends_on:
      rust-tests-server:
        condition: process_completed_successfully
      rust-tests-cli:
        condition: process_completed_successfully
      rust-tests-core:
        condition: process_completed_successfully
      api-tests:
        condition: process_completed_successfully
