/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateClientLogRequest,
  CreateClientLogResponse,
  ErrorResponse,
  GetClientLogResponse,
  ListClientLogsResponse,
} from '../models/index';
import {
    CreateClientLogRequestFromJSON,
    CreateClientLogRequestToJSON,
    CreateClientLogResponseFromJSON,
    CreateClientLogResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    GetClientLogResponseFromJSON,
    GetClientLogResponseToJSON,
    ListClientLogsResponseFromJSON,
    ListClientLogsResponseToJSON,
} from '../models/index';

export interface CreateClientLogOperationRequest {
    createClientLogRequest: CreateClientLogRequest;
}

export interface GetClientLogRequest {
    id: string;
}

/**
 * 
 */
export class ClientLogsApi extends runtime.BaseAPI {

    /**
     */
    async createClientLogRaw(requestParameters: CreateClientLogOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateClientLogResponse>> {
        if (requestParameters['createClientLogRequest'] == null) {
            throw new runtime.RequiredError(
                'createClientLogRequest',
                'Required parameter "createClientLogRequest" was null or undefined when calling createClientLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/client-logs`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateClientLogRequestToJSON(requestParameters['createClientLogRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateClientLogResponseFromJSON(jsonValue));
    }

    /**
     */
    async createClientLog(requestParameters: CreateClientLogOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateClientLogResponse> {
        const response = await this.createClientLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getClientLogRaw(requestParameters: GetClientLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetClientLogResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getClientLog().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/client-logs/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetClientLogResponseFromJSON(jsonValue));
    }

    /**
     */
    async getClientLog(requestParameters: GetClientLogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetClientLogResponse> {
        const response = await this.getClientLogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async listClientLogsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListClientLogsResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/client-logs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListClientLogsResponseFromJSON(jsonValue));
    }

    /**
     */
    async listClientLogs(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListClientLogsResponse> {
        const response = await this.listClientLogsRaw(initOverrides);
        return await response.value();
    }

}
