/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EnrichRequest,
  EnrichResponse,
  ErrorResponse,
} from '../models/index';
import {
    EnrichRequestFromJSON,
    EnrichRequestToJSON,
    EnrichResponseFromJSON,
    EnrichResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
} from '../models/index';

export interface EnrichRecipeRequest {
    enrichRequest: EnrichRequest;
}

/**
 * 
 */
export class EnrichApi extends runtime.BaseAPI {

    /**
     * This is a stateless endpoint that takes a recipe object and returns an enriched version. It does NOT modify any database records. The client can apply the enriched data via a normal PUT /api/recipes/{id} call.
     * Enrich a recipe using AI
     */
    async enrichRecipeRaw(requestParameters: EnrichRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnrichResponse>> {
        if (requestParameters['enrichRequest'] == null) {
            throw new runtime.RequiredError(
                'enrichRequest',
                'Required parameter "enrichRequest" was null or undefined when calling enrichRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/enrich`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: EnrichRequestToJSON(requestParameters['enrichRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnrichResponseFromJSON(jsonValue));
    }

    /**
     * This is a stateless endpoint that takes a recipe object and returns an enriched version. It does NOT modify any database records. The client can apply the enriched data via a normal PUT /api/recipes/{id} call.
     * Enrich a recipe using AI
     */
    async enrichRecipe(requestParameters: EnrichRecipeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnrichResponse> {
        const response = await this.enrichRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
