/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  ImportFromPhotosRequest,
  ImportFromPhotosResponse,
  ImportRecipeRequest,
  ImportRecipeResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    ImportFromPhotosRequestFromJSON,
    ImportFromPhotosRequestToJSON,
    ImportFromPhotosResponseFromJSON,
    ImportFromPhotosResponseToJSON,
    ImportRecipeRequestFromJSON,
    ImportRecipeRequestToJSON,
    ImportRecipeResponseFromJSON,
    ImportRecipeResponseToJSON,
} from '../models/index';

export interface ImportFromPhotosOperationRequest {
    importFromPhotosRequest: ImportFromPhotosRequest;
}

export interface ImportRecipeOperationRequest {
    importRecipeRequest: ImportRecipeRequest;
}

/**
 * 
 */
export class ImportApi extends runtime.BaseAPI {

    /**
     */
    async importFromPhotosRaw(requestParameters: ImportFromPhotosOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportFromPhotosResponse>> {
        if (requestParameters['importFromPhotosRequest'] == null) {
            throw new runtime.RequiredError(
                'importFromPhotosRequest',
                'Required parameter "importFromPhotosRequest" was null or undefined when calling importFromPhotos().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/import/photos`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportFromPhotosRequestToJSON(requestParameters['importFromPhotosRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportFromPhotosResponseFromJSON(jsonValue));
    }

    /**
     */
    async importFromPhotos(requestParameters: ImportFromPhotosOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportFromPhotosResponse> {
        const response = await this.importFromPhotosRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async importRecipeRaw(requestParameters: ImportRecipeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ImportRecipeResponse>> {
        if (requestParameters['importRecipeRequest'] == null) {
            throw new runtime.RequiredError(
                'importRecipeRequest',
                'Required parameter "importRecipeRequest" was null or undefined when calling importRecipe().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/import/recipe`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ImportRecipeRequestToJSON(requestParameters['importRecipeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ImportRecipeResponseFromJSON(jsonValue));
    }

    /**
     */
    async importRecipe(requestParameters: ImportRecipeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ImportRecipeResponse> {
        const response = await this.importRecipeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
