/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CaptureRequest,
  CaptureResponse,
  CreateScrapeRequest,
  CreateScrapeResponse,
  ErrorResponse,
  RetryScrapeResponse,
  ScrapeJobResponse,
} from '../models/index';
import {
    CaptureRequestFromJSON,
    CaptureRequestToJSON,
    CaptureResponseFromJSON,
    CaptureResponseToJSON,
    CreateScrapeRequestFromJSON,
    CreateScrapeRequestToJSON,
    CreateScrapeResponseFromJSON,
    CreateScrapeResponseToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    RetryScrapeResponseFromJSON,
    RetryScrapeResponseToJSON,
    ScrapeJobResponseFromJSON,
    ScrapeJobResponseToJSON,
} from '../models/index';

export interface CaptureOperationRequest {
    captureRequest: CaptureRequest;
}

export interface CreateScrapeOperationRequest {
    createScrapeRequest: CreateScrapeRequest;
}

export interface GetScrapeRequest {
    id: string;
}

export interface RetryScrapeRequest {
    id: string;
}

/**
 * 
 */
export class ScrapeApi extends runtime.BaseAPI {

    /**
     */
    async captureRaw(requestParameters: CaptureOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CaptureResponse>> {
        if (requestParameters['captureRequest'] == null) {
            throw new runtime.RequiredError(
                'captureRequest',
                'Required parameter "captureRequest" was null or undefined when calling capture().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scrape/capture`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CaptureRequestToJSON(requestParameters['captureRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CaptureResponseFromJSON(jsonValue));
    }

    /**
     */
    async capture(requestParameters: CaptureOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CaptureResponse> {
        const response = await this.captureRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async createScrapeRaw(requestParameters: CreateScrapeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateScrapeResponse>> {
        if (requestParameters['createScrapeRequest'] == null) {
            throw new runtime.RequiredError(
                'createScrapeRequest',
                'Required parameter "createScrapeRequest" was null or undefined when calling createScrape().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scrape`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateScrapeRequestToJSON(requestParameters['createScrapeRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateScrapeResponseFromJSON(jsonValue));
    }

    /**
     */
    async createScrape(requestParameters: CreateScrapeOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateScrapeResponse> {
        const response = await this.createScrapeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getScrapeRaw(requestParameters: GetScrapeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ScrapeJobResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getScrape().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scrape/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ScrapeJobResponseFromJSON(jsonValue));
    }

    /**
     */
    async getScrape(requestParameters: GetScrapeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ScrapeJobResponse> {
        const response = await this.getScrapeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async retryScrapeRaw(requestParameters: RetryScrapeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<RetryScrapeResponse>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling retryScrape().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer_auth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/scrape/{id}/retry`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => RetryScrapeResponseFromJSON(jsonValue));
    }

    /**
     */
    async retryScrape(requestParameters: RetryScrapeRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<RetryScrapeResponse> {
        const response = await this.retryScrapeRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
