/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookmarkletTokenResponse
 */
export interface BookmarkletTokenResponse {
    /**
     * A freshly minted, long-lived token scoped to the capture endpoints.
     * Embed it in the bookmarklet; it does not expire and does not invalidate
     * previously minted bookmarklet tokens.
     * @type {string}
     * @memberof BookmarkletTokenResponse
     */
    token: string;
}

/**
 * Check if a given object implements the BookmarkletTokenResponse interface.
 */
export function instanceOfBookmarkletTokenResponse(value: object): value is BookmarkletTokenResponse {
    if (!('token' in value) || value['token'] === undefined) return false;
    return true;
}

export function BookmarkletTokenResponseFromJSON(json: any): BookmarkletTokenResponse {
    return BookmarkletTokenResponseFromJSONTyped(json, false);
}

export function BookmarkletTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookmarkletTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'],
    };
}

export function BookmarkletTokenResponseToJSON(json: any): BookmarkletTokenResponse {
    return BookmarkletTokenResponseToJSONTyped(json, false);
}

export function BookmarkletTokenResponseToJSONTyped(value?: BookmarkletTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

