/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CalorieRange } from './CalorieRange';
import {
    CalorieRangeFromJSON,
    CalorieRangeFromJSONTyped,
    CalorieRangeToJSON,
    CalorieRangeToJSONTyped,
} from './CalorieRange';
import type { UnknownCalorieIngredient } from './UnknownCalorieIngredient';
import {
    UnknownCalorieIngredientFromJSON,
    UnknownCalorieIngredientFromJSONTyped,
    UnknownCalorieIngredientToJSON,
    UnknownCalorieIngredientToJSONTyped,
} from './UnknownCalorieIngredient';

/**
 * 
 * @export
 * @interface CalorieEstimateResponse
 */
export interface CalorieEstimateResponse {
    /**
     * Identifies the pinned source data, aliases, and calculation rules.
     * @type {string}
     * @memberof CalorieEstimateResponse
     */
    databaseVersion: string;
    /**
     * Null when no ingredient could be estimated. Otherwise a subtotal that may be partial.
     * @type {CalorieRange}
     * @memberof CalorieEstimateResponse
     */
    knownCalories?: CalorieRange | null;
    /**
     * 
     * @type {CalorieRange}
     * @memberof CalorieEstimateResponse
     */
    perServingCalories?: CalorieRange | null;
    /**
     * 
     * @type {string}
     * @memberof CalorieEstimateResponse
     */
    perServingSummary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CalorieEstimateResponse
     */
    summary: string;
    /**
     * 
     * @type {Array<UnknownCalorieIngredient>}
     * @memberof CalorieEstimateResponse
     */
    unknownIngredients: Array<UnknownCalorieIngredient>;
}

/**
 * Check if a given object implements the CalorieEstimateResponse interface.
 */
export function instanceOfCalorieEstimateResponse(value: object): value is CalorieEstimateResponse {
    if (!('databaseVersion' in value) || value['databaseVersion'] === undefined) return false;
    if (!('summary' in value) || value['summary'] === undefined) return false;
    if (!('unknownIngredients' in value) || value['unknownIngredients'] === undefined) return false;
    return true;
}

export function CalorieEstimateResponseFromJSON(json: any): CalorieEstimateResponse {
    return CalorieEstimateResponseFromJSONTyped(json, false);
}

export function CalorieEstimateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CalorieEstimateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'databaseVersion': json['database_version'],
        'knownCalories': json['known_calories'] == null ? undefined : CalorieRangeFromJSON(json['known_calories']),
        'perServingCalories': json['per_serving_calories'] == null ? undefined : CalorieRangeFromJSON(json['per_serving_calories']),
        'perServingSummary': json['per_serving_summary'] == null ? undefined : json['per_serving_summary'],
        'summary': json['summary'],
        'unknownIngredients': ((json['unknown_ingredients'] as Array<any>).map(UnknownCalorieIngredientFromJSON)),
    };
}

export function CalorieEstimateResponseToJSON(json: any): CalorieEstimateResponse {
    return CalorieEstimateResponseToJSONTyped(json, false);
}

export function CalorieEstimateResponseToJSONTyped(value?: CalorieEstimateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'database_version': value['databaseVersion'],
        'known_calories': CalorieRangeToJSON(value['knownCalories']),
        'per_serving_calories': CalorieRangeToJSON(value['perServingCalories']),
        'per_serving_summary': value['perServingSummary'],
        'summary': value['summary'],
        'unknown_ingredients': ((value['unknownIngredients'] as Array<any>).map(UnknownCalorieIngredientToJSON)),
    };
}

