/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaptureResponse
 */
export interface CaptureResponse {
    /**
     * The created recipe ID
     * @type {string}
     * @memberof CaptureResponse
     */
    recipeId: string;
    /**
     * The extracted recipe title
     * @type {string}
     * @memberof CaptureResponse
     */
    title: string;
}

/**
 * Check if a given object implements the CaptureResponse interface.
 */
export function instanceOfCaptureResponse(value: object): value is CaptureResponse {
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CaptureResponseFromJSON(json: any): CaptureResponse {
    return CaptureResponseFromJSONTyped(json, false);
}

export function CaptureResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptureResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'recipeId': json['recipe_id'],
        'title': json['title'],
    };
}

export function CaptureResponseToJSON(json: any): CaptureResponse {
    return CaptureResponseToJSONTyped(json, false);
}

export function CaptureResponseToJSONTyped(value?: CaptureResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'recipe_id': value['recipeId'],
        'title': value['title'],
    };
}

