/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CaptureRequest
 */
export interface CaptureRequest {
    /**
     * The HTML content of the page to extract a recipe from
     * @type {string}
     * @memberof CaptureRequest
     */
    html: string;
    /**
     * The URL the HTML came from (used for source attribution)
     * @type {string}
     * @memberof CaptureRequest
     */
    sourceUrl: string;
}

/**
 * Check if a given object implements the CaptureRequest interface.
 */
export function instanceOfCaptureRequest(value: object): value is CaptureRequest {
    if (!('html' in value) || value['html'] === undefined) return false;
    if (!('sourceUrl' in value) || value['sourceUrl'] === undefined) return false;
    return true;
}

export function CaptureRequestFromJSON(json: any): CaptureRequest {
    return CaptureRequestFromJSONTyped(json, false);
}

export function CaptureRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CaptureRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'html': json['html'],
        'sourceUrl': json['source_url'],
    };
}

export function CaptureRequestToJSON(json: any): CaptureRequest {
    return CaptureRequestToJSONTyped(json, false);
}

export function CaptureRequestToJSONTyped(value?: CaptureRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'html': value['html'],
        'source_url': value['sourceUrl'],
    };
}

