/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClearCheckedResponse
 */
export interface ClearCheckedResponse {
    /**
     * 
     * @type {number}
     * @memberof ClearCheckedResponse
     */
    deletedCount: number;
}

/**
 * Check if a given object implements the ClearCheckedResponse interface.
 */
export function instanceOfClearCheckedResponse(value: object): value is ClearCheckedResponse {
    if (!('deletedCount' in value) || value['deletedCount'] === undefined) return false;
    return true;
}

export function ClearCheckedResponseFromJSON(json: any): ClearCheckedResponse {
    return ClearCheckedResponseFromJSONTyped(json, false);
}

export function ClearCheckedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClearCheckedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'deletedCount': json['deleted_count'],
    };
}

export function ClearCheckedResponseToJSON(json: any): ClearCheckedResponse {
    return ClearCheckedResponseToJSONTyped(json, false);
}

export function ClearCheckedResponseToJSONTyped(value?: ClearCheckedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'deleted_count': value['deletedCount'],
    };
}

