/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientLogSummary
 */
export interface ClientLogSummary {
    /**
     * 
     * @type {string}
     * @memberof ClientLogSummary
     */
    appVersion?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ClientLogSummary
     */
    contentLength: number;
    /**
     * 
     * @type {Date}
     * @memberof ClientLogSummary
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof ClientLogSummary
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof ClientLogSummary
     */
    osInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ClientLogSummary
     */
    platform: string;
}

/**
 * Check if a given object implements the ClientLogSummary interface.
 */
export function instanceOfClientLogSummary(value: object): value is ClientLogSummary {
    if (!('contentLength' in value) || value['contentLength'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function ClientLogSummaryFromJSON(json: any): ClientLogSummary {
    return ClientLogSummaryFromJSONTyped(json, false);
}

export function ClientLogSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientLogSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'appVersion': json['app_version'] == null ? undefined : json['app_version'],
        'contentLength': json['content_length'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'osInfo': json['os_info'] == null ? undefined : json['os_info'],
        'platform': json['platform'],
    };
}

export function ClientLogSummaryToJSON(json: any): ClientLogSummary {
    return ClientLogSummaryToJSONTyped(json, false);
}

export function ClientLogSummaryToJSONTyped(value?: ClientLogSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_version': value['appVersion'],
        'content_length': value['contentLength'],
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'os_info': value['osInfo'],
        'platform': value['platform'],
    };
}

