/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateScrapeResponse
 */
export interface CreateScrapeResponse {
    /**
     * The scrape job ID
     * @type {string}
     * @memberof CreateScrapeResponse
     */
    id: string;
    /**
     * Current job status
     * @type {string}
     * @memberof CreateScrapeResponse
     */
    status: string;
}

/**
 * Check if a given object implements the CreateScrapeResponse interface.
 */
export function instanceOfCreateScrapeResponse(value: object): value is CreateScrapeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CreateScrapeResponseFromJSON(json: any): CreateScrapeResponse {
    return CreateScrapeResponseFromJSONTyped(json, false);
}

export function CreateScrapeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScrapeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
    };
}

export function CreateScrapeResponseToJSON(json: any): CreateScrapeResponse {
    return CreateScrapeResponseToJSONTyped(json, false);
}

export function CreateScrapeResponseToJSONTyped(value?: CreateScrapeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
    };
}

