/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ingredient } from './Ingredient';
import {
    IngredientFromJSON,
    IngredientFromJSONTyped,
    IngredientToJSON,
    IngredientToJSONTyped,
} from './Ingredient';

/**
 * 
 * @export
 * @interface CreateRecipeRequest
 */
export interface CreateRecipeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    description?: string | null;
    /**
     * 
     * @type {Array<Ingredient>}
     * @memberof CreateRecipeRequest
     */
    ingredients: Array<Ingredient>;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    instructions: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRecipeRequest
     */
    photoIds?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    sourceName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    sourceUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateRecipeRequest
     */
    tags?: Array<string> | null;
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeRequest
     */
    title: string;
}

/**
 * Check if a given object implements the CreateRecipeRequest interface.
 */
export function instanceOfCreateRecipeRequest(value: object): value is CreateRecipeRequest {
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function CreateRecipeRequestFromJSON(json: any): CreateRecipeRequest {
    return CreateRecipeRequestFromJSONTyped(json, false);
}

export function CreateRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientFromJSON)),
        'instructions': json['instructions'],
        'photoIds': json['photo_ids'] == null ? undefined : json['photo_ids'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'sourceUrl': json['source_url'] == null ? undefined : json['source_url'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'],
    };
}

export function CreateRecipeRequestToJSON(json: any): CreateRecipeRequest {
    return CreateRecipeRequestToJSONTyped(json, false);
}

export function CreateRecipeRequestToJSONTyped(value?: CreateRecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientToJSON)),
        'instructions': value['instructions'],
        'photo_ids': value['photoIds'],
        'source_name': value['sourceName'],
        'source_url': value['sourceUrl'],
        'tags': value['tags'],
        'title': value['title'],
    };
}

