/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateMealPlanResponse
 */
export interface CreateMealPlanResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateMealPlanResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreateMealPlanResponse interface.
 */
export function instanceOfCreateMealPlanResponse(value: object): value is CreateMealPlanResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateMealPlanResponseFromJSON(json: any): CreateMealPlanResponse {
    return CreateMealPlanResponseFromJSONTyped(json, false);
}

export function CreateMealPlanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMealPlanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateMealPlanResponseToJSON(json: any): CreateMealPlanResponse {
    return CreateMealPlanResponseToJSONTyped(json, false);
}

export function CreateMealPlanResponseToJSONTyped(value?: CreateMealPlanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

