/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateClientLogRequest
 */
export interface CreateClientLogRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateClientLogRequest
     */
    appVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateClientLogRequest
     */
    content: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClientLogRequest
     */
    osInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateClientLogRequest
     */
    platform: string;
}

/**
 * Check if a given object implements the CreateClientLogRequest interface.
 */
export function instanceOfCreateClientLogRequest(value: object): value is CreateClientLogRequest {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function CreateClientLogRequestFromJSON(json: any): CreateClientLogRequest {
    return CreateClientLogRequestFromJSONTyped(json, false);
}

export function CreateClientLogRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClientLogRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'appVersion': json['app_version'] == null ? undefined : json['app_version'],
        'content': json['content'],
        'osInfo': json['os_info'] == null ? undefined : json['os_info'],
        'platform': json['platform'],
    };
}

export function CreateClientLogRequestToJSON(json: any): CreateClientLogRequest {
    return CreateClientLogRequestToJSONTyped(json, false);
}

export function CreateClientLogRequestToJSONTyped(value?: CreateClientLogRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_version': value['appVersion'],
        'content': value['content'],
        'os_info': value['osInfo'],
        'platform': value['platform'],
    };
}

