/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MealType } from './MealType';
import {
    MealTypeFromJSON,
    MealTypeFromJSONTyped,
    MealTypeToJSON,
    MealTypeToJSONTyped,
} from './MealType';

/**
 * 
 * @export
 * @interface CreateMealPlanRequest
 */
export interface CreateMealPlanRequest {
    /**
     * 
     * @type {Date}
     * @memberof CreateMealPlanRequest
     */
    mealDate: Date;
    /**
     * 
     * @type {MealType}
     * @memberof CreateMealPlanRequest
     */
    mealType: MealType;
    /**
     * 
     * @type {string}
     * @memberof CreateMealPlanRequest
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateMealPlanRequest
     */
    recipeId: string;
}



/**
 * Check if a given object implements the CreateMealPlanRequest interface.
 */
export function instanceOfCreateMealPlanRequest(value: object): value is CreateMealPlanRequest {
    if (!('mealDate' in value) || value['mealDate'] === undefined) return false;
    if (!('mealType' in value) || value['mealType'] === undefined) return false;
    if (!('recipeId' in value) || value['recipeId'] === undefined) return false;
    return true;
}

export function CreateMealPlanRequestFromJSON(json: any): CreateMealPlanRequest {
    return CreateMealPlanRequestFromJSONTyped(json, false);
}

export function CreateMealPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateMealPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mealDate': (new Date(json['meal_date'])),
        'mealType': MealTypeFromJSON(json['meal_type']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'recipeId': json['recipe_id'],
    };
}

export function CreateMealPlanRequestToJSON(json: any): CreateMealPlanRequest {
    return CreateMealPlanRequestToJSONTyped(json, false);
}

export function CreateMealPlanRequestToJSONTyped(value?: CreateMealPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meal_date': value['mealDate'].toISOString().substring(0,10),
        'meal_type': MealTypeToJSON(value['mealType']),
        'notes': value['notes'],
        'recipe_id': value['recipeId'],
    };
}

