/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateShoppingListItemRequest
 */
export interface CreateShoppingListItemRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateShoppingListItemRequest
     */
    amount?: string | null;
    /**
     * Client-generated ID for offline sync
     * @type {string}
     * @memberof CreateShoppingListItemRequest
     */
    clientId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateShoppingListItemRequest
     */
    item: string;
    /**
     * 
     * @type {string}
     * @memberof CreateShoppingListItemRequest
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateShoppingListItemRequest
     */
    sourceRecipeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateShoppingListItemRequest
     */
    sourceRecipeTitle?: string | null;
}

/**
 * Check if a given object implements the CreateShoppingListItemRequest interface.
 */
export function instanceOfCreateShoppingListItemRequest(value: object): value is CreateShoppingListItemRequest {
    if (!('item' in value) || value['item'] === undefined) return false;
    return true;
}

export function CreateShoppingListItemRequestFromJSON(json: any): CreateShoppingListItemRequest {
    return CreateShoppingListItemRequestFromJSONTyped(json, false);
}

export function CreateShoppingListItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShoppingListItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'item': json['item'],
        'note': json['note'] == null ? undefined : json['note'],
        'sourceRecipeId': json['source_recipe_id'] == null ? undefined : json['source_recipe_id'],
        'sourceRecipeTitle': json['source_recipe_title'] == null ? undefined : json['source_recipe_title'],
    };
}

export function CreateShoppingListItemRequestToJSON(json: any): CreateShoppingListItemRequest {
    return CreateShoppingListItemRequestToJSONTyped(json, false);
}

export function CreateShoppingListItemRequestToJSONTyped(value?: CreateShoppingListItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'client_id': value['clientId'],
        'item': value['item'],
        'note': value['note'],
        'source_recipe_id': value['sourceRecipeId'],
        'source_recipe_title': value['sourceRecipeTitle'],
    };
}

