/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateTagResponse
 */
export interface CreateTagResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateTagResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof CreateTagResponse
     */
    name: string;
}

/**
 * Check if a given object implements the CreateTagResponse interface.
 */
export function instanceOfCreateTagResponse(value: object): value is CreateTagResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function CreateTagResponseFromJSON(json: any): CreateTagResponse {
    return CreateTagResponseFromJSONTyped(json, false);
}

export function CreateTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function CreateTagResponseToJSON(json: any): CreateTagResponse {
    return CreateTagResponseToJSONTyped(json, false);
}

export function CreateTagResponseToJSONTyped(value?: CreateTagResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

