/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateShoppingListItemRequest } from './CreateShoppingListItemRequest';
import {
    CreateShoppingListItemRequestFromJSON,
    CreateShoppingListItemRequestFromJSONTyped,
    CreateShoppingListItemRequestToJSON,
    CreateShoppingListItemRequestToJSONTyped,
} from './CreateShoppingListItemRequest';

/**
 * 
 * @export
 * @interface CreateShoppingListRequest
 */
export interface CreateShoppingListRequest {
    /**
     * 
     * @type {Array<CreateShoppingListItemRequest>}
     * @memberof CreateShoppingListRequest
     */
    items: Array<CreateShoppingListItemRequest>;
}

/**
 * Check if a given object implements the CreateShoppingListRequest interface.
 */
export function instanceOfCreateShoppingListRequest(value: object): value is CreateShoppingListRequest {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function CreateShoppingListRequestFromJSON(json: any): CreateShoppingListRequest {
    return CreateShoppingListRequestFromJSONTyped(json, false);
}

export function CreateShoppingListRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateShoppingListRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(CreateShoppingListItemRequestFromJSON)),
    };
}

export function CreateShoppingListRequestToJSON(json: any): CreateShoppingListRequest {
    return CreateShoppingListRequestToJSONTyped(json, false);
}

export function CreateShoppingListRequestToJSONTyped(value?: CreateShoppingListRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(CreateShoppingListItemRequestToJSON)),
    };
}

