/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateRecipeResponse
 */
export interface CreateRecipeResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateRecipeResponse
     */
    id: string;
}

/**
 * Check if a given object implements the CreateRecipeResponse interface.
 */
export function instanceOfCreateRecipeResponse(value: object): value is CreateRecipeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function CreateRecipeResponseFromJSON(json: any): CreateRecipeResponse {
    return CreateRecipeResponseFromJSONTyped(json, false);
}

export function CreateRecipeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateRecipeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateRecipeResponseToJSON(json: any): CreateRecipeResponse {
    return CreateRecipeResponseToJSONTyped(json, false);
}

export function CreateRecipeResponseToJSONTyped(value?: CreateRecipeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

