/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateScrapeRequest
 */
export interface CreateScrapeRequest {
    /**
     * URL to scrape for recipe data
     * @type {string}
     * @memberof CreateScrapeRequest
     */
    url: string;
}

/**
 * Check if a given object implements the CreateScrapeRequest interface.
 */
export function instanceOfCreateScrapeRequest(value: object): value is CreateScrapeRequest {
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function CreateScrapeRequestFromJSON(json: any): CreateScrapeRequest {
    return CreateScrapeRequestFromJSONTyped(json, false);
}

export function CreateScrapeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateScrapeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'],
    };
}

export function CreateScrapeRequestToJSON(json: any): CreateScrapeRequest {
    return CreateScrapeRequestToJSONTyped(json, false);
}

export function CreateScrapeRequestToJSONTyped(value?: CreateScrapeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

