/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeContent } from './RecipeContent';
import {
    RecipeContentFromJSON,
    RecipeContentFromJSONTyped,
    RecipeContentToJSON,
    RecipeContentToJSONTyped,
} from './RecipeContent';

/**
 * Request body for custom enrichment.
 * @export
 * @interface CustomEnrichRequest
 */
export interface CustomEnrichRequest {
    /**
     * 
     * @type {string}
     * @memberof CustomEnrichRequest
     */
    instruction: string;
    /**
     * 
     * @type {RecipeContent}
     * @memberof CustomEnrichRequest
     */
    recipe: RecipeContent;
}

/**
 * Check if a given object implements the CustomEnrichRequest interface.
 */
export function instanceOfCustomEnrichRequest(value: object): value is CustomEnrichRequest {
    if (!('instruction' in value) || value['instruction'] === undefined) return false;
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    return true;
}

export function CustomEnrichRequestFromJSON(json: any): CustomEnrichRequest {
    return CustomEnrichRequestFromJSONTyped(json, false);
}

export function CustomEnrichRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CustomEnrichRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'instruction': json['instruction'],
        'recipe': RecipeContentFromJSON(json['recipe']),
    };
}

export function CustomEnrichRequestToJSON(json: any): CustomEnrichRequest {
    return CustomEnrichRequestToJSONTyped(json, false);
}

export function CustomEnrichRequestToJSONTyped(value?: CustomEnrichRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'instruction': value['instruction'],
        'recipe': RecipeContentToJSON(value['recipe']),
    };
}

