/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Approximate grams for one ingredient line: oz/lb converted, or a volume
 * through the catalog's density for the food. Computed on every read and
 * never stored, so catalog improvements reach every recipe; never send these
 * back when saving.
 * @export
 * @interface DerivedMeasurement
 */
export interface DerivedMeasurement {
    /**
     * 
     * @type {string}
     * @memberof DerivedMeasurement
     */
    amount: string;
    /**
     * Index of the ingredient this belongs to.
     * @type {number}
     * @memberof DerivedMeasurement
     */
    ingredientIndex: number;
    /**
     * 
     * @type {string}
     * @memberof DerivedMeasurement
     */
    unit: string;
}

/**
 * Check if a given object implements the DerivedMeasurement interface.
 */
export function instanceOfDerivedMeasurement(value: object): value is DerivedMeasurement {
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('ingredientIndex' in value) || value['ingredientIndex'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function DerivedMeasurementFromJSON(json: any): DerivedMeasurement {
    return DerivedMeasurementFromJSONTyped(json, false);
}

export function DerivedMeasurementFromJSONTyped(json: any, ignoreDiscriminator: boolean): DerivedMeasurement {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'],
        'ingredientIndex': json['ingredient_index'],
        'unit': json['unit'],
    };
}

export function DerivedMeasurementToJSON(json: any): DerivedMeasurement {
    return DerivedMeasurementToJSONTyped(json, false);
}

export function DerivedMeasurementToJSONTyped(value?: DerivedMeasurement | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'ingredient_index': value['ingredientIndex'],
        'unit': value['unit'],
    };
}

