/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeContent } from './RecipeContent';
import {
    RecipeContentFromJSON,
    RecipeContentFromJSONTyped,
    RecipeContentToJSON,
    RecipeContentToJSONTyped,
} from './RecipeContent';

/**
 * Request to enrich a recipe.
 * @export
 * @interface EnrichRequest
 */
export interface EnrichRequest {
    /**
     * The type of enrichment to apply (e.g., "normalize_ingredients").
     * @type {string}
     * @memberof EnrichRequest
     */
    enrichmentType: string;
    /**
     * The recipe content to enrich.
     * @type {RecipeContent}
     * @memberof EnrichRequest
     */
    recipe: RecipeContent;
}

/**
 * Check if a given object implements the EnrichRequest interface.
 */
export function instanceOfEnrichRequest(value: object): value is EnrichRequest {
    if (!('enrichmentType' in value) || value['enrichmentType'] === undefined) return false;
    if (!('recipe' in value) || value['recipe'] === undefined) return false;
    return true;
}

export function EnrichRequestFromJSON(json: any): EnrichRequest {
    return EnrichRequestFromJSONTyped(json, false);
}

export function EnrichRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'enrichmentType': json['enrichment_type'],
        'recipe': RecipeContentFromJSON(json['recipe']),
    };
}

export function EnrichRequestToJSON(json: any): EnrichRequest {
    return EnrichRequestToJSONTyped(json, false);
}

export function EnrichRequestToJSONTyped(value?: EnrichRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'enrichment_type': value['enrichmentType'],
        'recipe': RecipeContentToJSON(value['recipe']),
    };
}

