/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Information about an enrichment type for the API.
 * @export
 * @interface EnrichmentInfo
 */
export interface EnrichmentInfo {
    /**
     * 
     * @type {string}
     * @memberof EnrichmentInfo
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentInfo
     */
    displayName: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EnrichmentInfo
     */
    outputFields: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof EnrichmentInfo
     */
    type: string;
}

/**
 * Check if a given object implements the EnrichmentInfo interface.
 */
export function instanceOfEnrichmentInfo(value: object): value is EnrichmentInfo {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('outputFields' in value) || value['outputFields'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function EnrichmentInfoFromJSON(json: any): EnrichmentInfo {
    return EnrichmentInfoFromJSONTyped(json, false);
}

export function EnrichmentInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnrichmentInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'displayName': json['display_name'],
        'outputFields': json['output_fields'],
        'type': json['type'],
    };
}

export function EnrichmentInfoToJSON(json: any): EnrichmentInfo {
    return EnrichmentInfoToJSONTyped(json, false);
}

export function EnrichmentInfoToJSONTyped(value?: EnrichmentInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'display_name': value['displayName'],
        'output_fields': value['outputFields'],
        'type': value['type'],
    };
}

