/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Machine-readable error code surfaced in every error response.
 * 
 * Clients branch on this instead of parsing the human-readable `error`
 * message or guessing from the HTTP status, so changing the wording of a
 * message is never a contract change. Each code maps to exactly one HTTP
 * status (see [`ErrorCode::status`]).
 * @export
 */
export const ErrorCode = {
    NotFound: 'not_found',
    InvalidRequest: 'invalid_request',
    Conflict: 'conflict',
    Unauthorized: 'unauthorized',
    PayloadTooLarge: 'payload_too_large',
    ServiceUnavailable: 'service_unavailable',
    Internal: 'internal'
} as const;
export type ErrorCode = typeof ErrorCode[keyof typeof ErrorCode];


export function instanceOfErrorCode(value: any): boolean {
    for (const key in ErrorCode) {
        if (Object.prototype.hasOwnProperty.call(ErrorCode, key)) {
            if (ErrorCode[key as keyof typeof ErrorCode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ErrorCodeFromJSON(json: any): ErrorCode {
    return ErrorCodeFromJSONTyped(json, false);
}

export function ErrorCodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorCode {
    return json as ErrorCode;
}

export function ErrorCodeToJSON(value?: ErrorCode | null): any {
    return value as any;
}

export function ErrorCodeToJSONTyped(value: any, ignoreDiscriminator: boolean): ErrorCode {
    return value as ErrorCode;
}

