/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ingredient } from './Ingredient';
import {
    IngredientFromJSON,
    IngredientFromJSONTyped,
    IngredientToJSON,
    IngredientToJSONTyped,
} from './Ingredient';

/**
 * 
 * @export
 * @interface EstimateCaloriesRequest
 */
export interface EstimateCaloriesRequest {
    /**
     * 
     * @type {Array<Ingredient>}
     * @memberof EstimateCaloriesRequest
     */
    ingredients: Array<Ingredient>;
    /**
     * Multiplier applied to the whole recipe, including its serving count.
     * @type {number}
     * @memberof EstimateCaloriesRequest
     */
    scale: number;
    /**
     * Original, unscaled serving count. Yield text is not interpreted as a count.
     * @type {string}
     * @memberof EstimateCaloriesRequest
     */
    servings?: string | null;
}

/**
 * Check if a given object implements the EstimateCaloriesRequest interface.
 */
export function instanceOfEstimateCaloriesRequest(value: object): value is EstimateCaloriesRequest {
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('scale' in value) || value['scale'] === undefined) return false;
    return true;
}

export function EstimateCaloriesRequestFromJSON(json: any): EstimateCaloriesRequest {
    return EstimateCaloriesRequestFromJSONTyped(json, false);
}

export function EstimateCaloriesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): EstimateCaloriesRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientFromJSON)),
        'scale': json['scale'],
        'servings': json['servings'] == null ? undefined : json['servings'],
    };
}

export function EstimateCaloriesRequestToJSON(json: any): EstimateCaloriesRequest {
    return EstimateCaloriesRequestToJSONTyped(json, false);
}

export function EstimateCaloriesRequestToJSONTyped(value?: EstimateCaloriesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientToJSON)),
        'scale': value['scale'],
        'servings': value['servings'],
    };
}

