/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeneratePhotoResponse
 */
export interface GeneratePhotoResponse {
    /**
     * 
     * @type {string}
     * @memberof GeneratePhotoResponse
     */
    photoId: string;
    /**
     * 
     * @type {string}
     * @memberof GeneratePhotoResponse
     */
    versionId: string;
}

/**
 * Check if a given object implements the GeneratePhotoResponse interface.
 */
export function instanceOfGeneratePhotoResponse(value: object): value is GeneratePhotoResponse {
    if (!('photoId' in value) || value['photoId'] === undefined) return false;
    if (!('versionId' in value) || value['versionId'] === undefined) return false;
    return true;
}

export function GeneratePhotoResponseFromJSON(json: any): GeneratePhotoResponse {
    return GeneratePhotoResponseFromJSONTyped(json, false);
}

export function GeneratePhotoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeneratePhotoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'photoId': json['photo_id'],
        'versionId': json['version_id'],
    };
}

export function GeneratePhotoResponseToJSON(json: any): GeneratePhotoResponse {
    return GeneratePhotoResponseToJSONTyped(json, false);
}

export function GeneratePhotoResponseToJSONTyped(value?: GeneratePhotoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'photo_id': value['photoId'],
        'version_id': value['versionId'],
    };
}

