/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateDescriptionResponse
 */
export interface GenerateDescriptionResponse {
    /**
     * 
     * @type {boolean}
     * @memberof GenerateDescriptionResponse
     */
    cached: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateDescriptionResponse
     */
    changed: boolean;
    /**
     * 
     * @type {string}
     * @memberof GenerateDescriptionResponse
     */
    generatedDescription: string;
    /**
     * 
     * @type {string}
     * @memberof GenerateDescriptionResponse
     */
    originalDescription?: string | null;
}

/**
 * Check if a given object implements the GenerateDescriptionResponse interface.
 */
export function instanceOfGenerateDescriptionResponse(value: object): value is GenerateDescriptionResponse {
    if (!('cached' in value) || value['cached'] === undefined) return false;
    if (!('changed' in value) || value['changed'] === undefined) return false;
    if (!('generatedDescription' in value) || value['generatedDescription'] === undefined) return false;
    return true;
}

export function GenerateDescriptionResponseFromJSON(json: any): GenerateDescriptionResponse {
    return GenerateDescriptionResponseFromJSONTyped(json, false);
}

export function GenerateDescriptionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateDescriptionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cached': json['cached'],
        'changed': json['changed'],
        'generatedDescription': json['generated_description'],
        'originalDescription': json['original_description'] == null ? undefined : json['original_description'],
    };
}

export function GenerateDescriptionResponseToJSON(json: any): GenerateDescriptionResponse {
    return GenerateDescriptionResponseToJSONTyped(json, false);
}

export function GenerateDescriptionResponseToJSONTyped(value?: GenerateDescriptionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cached': value['cached'],
        'changed': value['changed'],
        'generated_description': value['generatedDescription'],
        'original_description': value['originalDescription'],
    };
}

