/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetClientLogResponse
 */
export interface GetClientLogResponse {
    /**
     * 
     * @type {string}
     * @memberof GetClientLogResponse
     */
    appVersion?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetClientLogResponse
     */
    content: string;
    /**
     * 
     * @type {Date}
     * @memberof GetClientLogResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof GetClientLogResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof GetClientLogResponse
     */
    osInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof GetClientLogResponse
     */
    platform: string;
}

/**
 * Check if a given object implements the GetClientLogResponse interface.
 */
export function instanceOfGetClientLogResponse(value: object): value is GetClientLogResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('platform' in value) || value['platform'] === undefined) return false;
    return true;
}

export function GetClientLogResponseFromJSON(json: any): GetClientLogResponse {
    return GetClientLogResponseFromJSONTyped(json, false);
}

export function GetClientLogResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetClientLogResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'appVersion': json['app_version'] == null ? undefined : json['app_version'],
        'content': json['content'],
        'createdAt': (new Date(json['created_at'])),
        'id': json['id'],
        'osInfo': json['os_info'] == null ? undefined : json['os_info'],
        'platform': json['platform'],
    };
}

export function GetClientLogResponseToJSON(json: any): GetClientLogResponse {
    return GetClientLogResponseToJSONTyped(json, false);
}

export function GetClientLogResponseToJSONTyped(value?: GetClientLogResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_version': value['appVersion'],
        'content': value['content'],
        'created_at': value['createdAt'].toISOString(),
        'id': value['id'],
        'os_info': value['osInfo'],
        'platform': value['platform'],
    };
}

