/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportRawRecipe } from './ImportRawRecipe';
import {
    ImportRawRecipeFromJSON,
    ImportRawRecipeFromJSONTyped,
    ImportRawRecipeToJSON,
    ImportRawRecipeToJSONTyped,
} from './ImportRawRecipe';
import type { ImportExtractionMethod } from './ImportExtractionMethod';
import {
    ImportExtractionMethodFromJSON,
    ImportExtractionMethodFromJSONTyped,
    ImportExtractionMethodToJSON,
    ImportExtractionMethodToJSONTyped,
} from './ImportExtractionMethod';

/**
 * Request body for importing a recipe
 * @export
 * @interface ImportRecipeRequest
 */
export interface ImportRecipeRequest {
    /**
     * The extraction/import method used
     * @type {ImportExtractionMethod}
     * @memberof ImportRecipeRequest
     */
    extractionMethod: ImportExtractionMethod;
    /**
     * Client-chosen key for this import. Resubmitting a key the user already
     * used returns the original job (200) instead of creating another recipe;
     * the resubmission's photo_ids are then ignored.
     * @type {string}
     * @memberof ImportRecipeRequest
     */
    idempotencyKey?: string | null;
    /**
     * Photo IDs that have already been uploaded via POST /api/photos
     * @type {Array<string>}
     * @memberof ImportRecipeRequest
     */
    photoIds: Array<string>;
    /**
     * The raw recipe data (converted from import source by client)
     * @type {ImportRawRecipe}
     * @memberof ImportRecipeRequest
     */
    rawRecipe: ImportRawRecipe;
}



/**
 * Check if a given object implements the ImportRecipeRequest interface.
 */
export function instanceOfImportRecipeRequest(value: object): value is ImportRecipeRequest {
    if (!('extractionMethod' in value) || value['extractionMethod'] === undefined) return false;
    if (!('photoIds' in value) || value['photoIds'] === undefined) return false;
    if (!('rawRecipe' in value) || value['rawRecipe'] === undefined) return false;
    return true;
}

export function ImportRecipeRequestFromJSON(json: any): ImportRecipeRequest {
    return ImportRecipeRequestFromJSONTyped(json, false);
}

export function ImportRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'extractionMethod': ImportExtractionMethodFromJSON(json['extraction_method']),
        'idempotencyKey': json['idempotency_key'] == null ? undefined : json['idempotency_key'],
        'photoIds': json['photo_ids'],
        'rawRecipe': ImportRawRecipeFromJSON(json['raw_recipe']),
    };
}

export function ImportRecipeRequestToJSON(json: any): ImportRecipeRequest {
    return ImportRecipeRequestToJSONTyped(json, false);
}

export function ImportRecipeRequestToJSONTyped(value?: ImportRecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'extraction_method': ImportExtractionMethodToJSON(value['extractionMethod']),
        'idempotency_key': value['idempotencyKey'],
        'photo_ids': value['photoIds'],
        'raw_recipe': ImportRawRecipeToJSON(value['rawRecipe']),
    };
}

