/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Extraction method for imported recipes (mirrors ramekin_core::ExtractionMethod)
 * @export
 */
export const ImportExtractionMethod = {
    JsonLd: 'json_ld',
    Microdata: 'microdata',
    Paprika: 'paprika'
} as const;
export type ImportExtractionMethod = typeof ImportExtractionMethod[keyof typeof ImportExtractionMethod];


export function instanceOfImportExtractionMethod(value: any): boolean {
    for (const key in ImportExtractionMethod) {
        if (Object.prototype.hasOwnProperty.call(ImportExtractionMethod, key)) {
            if (ImportExtractionMethod[key as keyof typeof ImportExtractionMethod] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ImportExtractionMethodFromJSON(json: any): ImportExtractionMethod {
    return ImportExtractionMethodFromJSONTyped(json, false);
}

export function ImportExtractionMethodFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportExtractionMethod {
    return json as ImportExtractionMethod;
}

export function ImportExtractionMethodToJSON(value?: ImportExtractionMethod | null): any {
    return value as any;
}

export function ImportExtractionMethodToJSONTyped(value: any, ignoreDiscriminator: boolean): ImportExtractionMethod {
    return value as ImportExtractionMethod;
}

