/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An import job submitted with an idempotency key
 * @export
 * @interface ImportJobKey
 */
export interface ImportJobKey {
    /**
     * 
     * @type {string}
     * @memberof ImportJobKey
     */
    idempotencyKey: string;
    /**
     * 
     * @type {string}
     * @memberof ImportJobKey
     */
    jobId: string;
}

/**
 * Check if a given object implements the ImportJobKey interface.
 */
export function instanceOfImportJobKey(value: object): value is ImportJobKey {
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    return true;
}

export function ImportJobKeyFromJSON(json: any): ImportJobKey {
    return ImportJobKeyFromJSONTyped(json, false);
}

export function ImportJobKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportJobKey {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotencyKey': json['idempotency_key'],
        'jobId': json['job_id'],
    };
}

export function ImportJobKeyToJSON(json: any): ImportJobKey {
    return ImportJobKeyToJSONTyped(json, false);
}

export function ImportJobKeyToJSONTyped(value?: ImportJobKey | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idempotency_key': value['idempotencyKey'],
        'job_id': value['jobId'],
    };
}

