/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response from recipe import
 * @export
 * @interface ImportRecipeResponse
 */
export interface ImportRecipeResponse {
    /**
     * The created job ID
     * @type {string}
     * @memberof ImportRecipeResponse
     */
    jobId: string;
    /**
     * Current job status
     * @type {string}
     * @memberof ImportRecipeResponse
     */
    status: string;
}

/**
 * Check if a given object implements the ImportRecipeResponse interface.
 */
export function instanceOfImportRecipeResponse(value: object): value is ImportRecipeResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ImportRecipeResponseFromJSON(json: any): ImportRecipeResponse {
    return ImportRecipeResponseFromJSONTyped(json, false);
}

export function ImportRecipeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportRecipeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'status': json['status'],
    };
}

export function ImportRecipeResponseToJSON(json: any): ImportRecipeResponse {
    return ImportRecipeResponseToJSONTyped(json, false);
}

export function ImportRecipeResponseToJSONTyped(value?: ImportRecipeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': value['status'],
    };
}

