/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientNameFailure
 */
export interface IngredientNameFailure {
    /**
     * 
     * @type {number}
     * @memberof IngredientNameFailure
     */
    attempts: number;
    /**
     * 
     * @type {string}
     * @memberof IngredientNameFailure
     */
    error: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientNameFailure
     */
    name: string;
}

/**
 * Check if a given object implements the IngredientNameFailure interface.
 */
export function instanceOfIngredientNameFailure(value: object): value is IngredientNameFailure {
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IngredientNameFailureFromJSON(json: any): IngredientNameFailure {
    return IngredientNameFailureFromJSONTyped(json, false);
}

export function IngredientNameFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientNameFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'attempts': json['attempts'],
        'error': json['error'],
        'name': json['name'],
    };
}

export function IngredientNameFailureToJSON(json: any): IngredientNameFailure {
    return IngredientNameFailureToJSONTyped(json, false);
}

export function IngredientNameFailureToJSONTyped(value?: IngredientNameFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempts': value['attempts'],
        'error': value['error'],
        'name': value['name'],
    };
}

