/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientNamesQueuedResponse
 */
export interface IngredientNamesQueuedResponse {
    /**
     * Names queued for resolution by this call.
     * @type {number}
     * @memberof IngredientNamesQueuedResponse
     */
    queued: number;
}

/**
 * Check if a given object implements the IngredientNamesQueuedResponse interface.
 */
export function instanceOfIngredientNamesQueuedResponse(value: object): value is IngredientNamesQueuedResponse {
    if (!('queued' in value) || value['queued'] === undefined) return false;
    return true;
}

export function IngredientNamesQueuedResponseFromJSON(json: any): IngredientNamesQueuedResponse {
    return IngredientNamesQueuedResponseFromJSONTyped(json, false);
}

export function IngredientNamesQueuedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientNamesQueuedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'queued': json['queued'],
    };
}

export function IngredientNamesQueuedResponseToJSON(json: any): IngredientNamesQueuedResponse {
    return IngredientNamesQueuedResponseToJSONTyped(json, false);
}

export function IngredientNamesQueuedResponseToJSONTyped(value?: IngredientNamesQueuedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'queued': value['queued'],
    };
}

