/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientNameFailure } from './IngredientNameFailure';
import {
    IngredientNameFailureFromJSON,
    IngredientNameFailureFromJSONTyped,
    IngredientNameFailureToJSON,
    IngredientNameFailureToJSONTyped,
} from './IngredientNameFailure';
import type { IngredientWeightsStatus } from './IngredientWeightsStatus';
import {
    IngredientWeightsStatusFromJSON,
    IngredientWeightsStatusFromJSONTyped,
    IngredientWeightsStatusToJSON,
    IngredientWeightsStatusToJSONTyped,
} from './IngredientWeightsStatus';

/**
 * 
 * @export
 * @interface IngredientNamesStatusResponse
 */
export interface IngredientNamesStatusResponse {
    /**
     * A real food no catalog entry matches, counted with the model's own
     * calories ("estimated calories").
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    estimated: number;
    /**
     * The last attempt failed; retry to try again.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    failed: number;
    /**
     * The most recent failures, failed re-asks included.
     * @type {Array<IngredientNameFailure>}
     * @memberof IngredientNamesStatusResponse
     */
    failures: Array<IngredientNameFailure>;
    /**
     * Resolved as not an ingredient (a heading, a serving note).
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    notFood: number;
    /**
     * Waiting for the background resolver.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    pending: number;
    /**
     * Re-asking with the current model failed; the earlier model's answer
     * is still used (and counted above). Retry to try again.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    reaskFailed: number;
    /**
     * Being asked again by the current model; the earlier model's answer
     * is used meanwhile (and counted above).
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    reasking: number;
    /**
     * Resolved to a catalog food or product (for an ambiguous name, the one
     * a recipe most likely means).
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    recognized: number;
    /**
     * Resolved, but the model couldn't tell; still unknown in estimates.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    unknown: number;
    /**
     * 
     * @type {IngredientWeightsStatus}
     * @memberof IngredientNamesStatusResponse
     */
    weights: IngredientWeightsStatus;
}

/**
 * Check if a given object implements the IngredientNamesStatusResponse interface.
 */
export function instanceOfIngredientNamesStatusResponse(value: object): value is IngredientNamesStatusResponse {
    if (!('estimated' in value) || value['estimated'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    if (!('notFood' in value) || value['notFood'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('reaskFailed' in value) || value['reaskFailed'] === undefined) return false;
    if (!('reasking' in value) || value['reasking'] === undefined) return false;
    if (!('recognized' in value) || value['recognized'] === undefined) return false;
    if (!('unknown' in value) || value['unknown'] === undefined) return false;
    if (!('weights' in value) || value['weights'] === undefined) return false;
    return true;
}

export function IngredientNamesStatusResponseFromJSON(json: any): IngredientNamesStatusResponse {
    return IngredientNamesStatusResponseFromJSONTyped(json, false);
}

export function IngredientNamesStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientNamesStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'estimated': json['estimated'],
        'failed': json['failed'],
        'failures': ((json['failures'] as Array<any>).map(IngredientNameFailureFromJSON)),
        'notFood': json['not_food'],
        'pending': json['pending'],
        'reaskFailed': json['reask_failed'],
        'reasking': json['reasking'],
        'recognized': json['recognized'],
        'unknown': json['unknown'],
        'weights': IngredientWeightsStatusFromJSON(json['weights']),
    };
}

export function IngredientNamesStatusResponseToJSON(json: any): IngredientNamesStatusResponse {
    return IngredientNamesStatusResponseToJSONTyped(json, false);
}

export function IngredientNamesStatusResponseToJSONTyped(value?: IngredientNamesStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'estimated': value['estimated'],
        'failed': value['failed'],
        'failures': ((value['failures'] as Array<any>).map(IngredientNameFailureToJSON)),
        'not_food': value['notFood'],
        'pending': value['pending'],
        'reask_failed': value['reaskFailed'],
        'reasking': value['reasking'],
        'recognized': value['recognized'],
        'unknown': value['unknown'],
        'weights': IngredientWeightsStatusToJSON(value['weights']),
    };
}

