/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientNameFailure } from './IngredientNameFailure';
import {
    IngredientNameFailureFromJSON,
    IngredientNameFailureFromJSONTyped,
    IngredientNameFailureToJSON,
    IngredientNameFailureToJSONTyped,
} from './IngredientNameFailure';

/**
 * 
 * @export
 * @interface IngredientNamesStatusResponse
 */
export interface IngredientNamesStatusResponse {
    /**
     * The last attempt failed; retry to try again.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    failed: number;
    /**
     * The most recent failures.
     * @type {Array<IngredientNameFailure>}
     * @memberof IngredientNamesStatusResponse
     */
    failures: Array<IngredientNameFailure>;
    /**
     * Resolved as not an ingredient (a heading, a serving note).
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    notFood: number;
    /**
     * Waiting for the background resolver.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    pending: number;
    /**
     * Resolved to a catalog food or product.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    recognized: number;
    /**
     * Resolved, but the model couldn't tell; still unknown in estimates.
     * @type {number}
     * @memberof IngredientNamesStatusResponse
     */
    unknown: number;
}

/**
 * Check if a given object implements the IngredientNamesStatusResponse interface.
 */
export function instanceOfIngredientNamesStatusResponse(value: object): value is IngredientNamesStatusResponse {
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    if (!('notFood' in value) || value['notFood'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if (!('recognized' in value) || value['recognized'] === undefined) return false;
    if (!('unknown' in value) || value['unknown'] === undefined) return false;
    return true;
}

export function IngredientNamesStatusResponseFromJSON(json: any): IngredientNamesStatusResponse {
    return IngredientNamesStatusResponseFromJSONTyped(json, false);
}

export function IngredientNamesStatusResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientNamesStatusResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'failed': json['failed'],
        'failures': ((json['failures'] as Array<any>).map(IngredientNameFailureFromJSON)),
        'notFood': json['not_food'],
        'pending': json['pending'],
        'recognized': json['recognized'],
        'unknown': json['unknown'],
    };
}

export function IngredientNamesStatusResponseToJSON(json: any): IngredientNamesStatusResponse {
    return IngredientNamesStatusResponseToJSONTyped(json, false);
}

export function IngredientNamesStatusResponseToJSONTyped(value?: IngredientNamesStatusResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'failed': value['failed'],
        'failures': ((value['failures'] as Array<any>).map(IngredientNameFailureToJSON)),
        'not_food': value['notFood'],
        'pending': value['pending'],
        'recognized': value['recognized'],
        'unknown': value['unknown'],
    };
}

