/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IngredientWeightFailure
 */
export interface IngredientWeightFailure {
    /**
     * 
     * @type {number}
     * @memberof IngredientWeightFailure
     */
    attempts: number;
    /**
     * 
     * @type {string}
     * @memberof IngredientWeightFailure
     */
    error: string;
    /**
     * The catalog food, as the catalog names it.
     * @type {string}
     * @memberof IngredientWeightFailure
     */
    food: string;
    /**
     * 
     * @type {string}
     * @memberof IngredientWeightFailure
     */
    unit: string;
}

/**
 * Check if a given object implements the IngredientWeightFailure interface.
 */
export function instanceOfIngredientWeightFailure(value: object): value is IngredientWeightFailure {
    if (!('attempts' in value) || value['attempts'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if (!('food' in value) || value['food'] === undefined) return false;
    if (!('unit' in value) || value['unit'] === undefined) return false;
    return true;
}

export function IngredientWeightFailureFromJSON(json: any): IngredientWeightFailure {
    return IngredientWeightFailureFromJSONTyped(json, false);
}

export function IngredientWeightFailureFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientWeightFailure {
    if (json == null) {
        return json;
    }
    return {
        
        'attempts': json['attempts'],
        'error': json['error'],
        'food': json['food'],
        'unit': json['unit'],
    };
}

export function IngredientWeightFailureToJSON(json: any): IngredientWeightFailure {
    return IngredientWeightFailureToJSONTyped(json, false);
}

export function IngredientWeightFailureToJSONTyped(value?: IngredientWeightFailure | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempts': value['attempts'],
        'error': value['error'],
        'food': value['food'],
        'unit': value['unit'],
    };
}

