/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IngredientWeightFailure } from './IngredientWeightFailure';
import {
    IngredientWeightFailureFromJSON,
    IngredientWeightFailureFromJSONTyped,
    IngredientWeightFailureToJSON,
    IngredientWeightFailureToJSONTyped,
} from './IngredientWeightFailure';

/**
 * Weights the catalog lacks for foods in the user's recipes (a density, or
 * a counted unit such as "bunch"), estimated in the background: every
 * estimate for those foods, whichever view queued it.
 * @export
 * @interface IngredientWeightsStatus
 */
export interface IngredientWeightsStatus {
    /**
     * Estimated; lines using one say "estimated weight".
     * @type {number}
     * @memberof IngredientWeightsStatus
     */
    estimated: number;
    /**
     * The last attempt failed; retry to try again.
     * @type {number}
     * @memberof IngredientWeightsStatus
     */
    failed: number;
    /**
     * The most recent failures.
     * @type {Array<IngredientWeightFailure>}
     * @memberof IngredientWeightsStatus
     */
    failures: Array<IngredientWeightFailure>;
    /**
     * The model said there's no typical weight; still unknown in estimates.
     * @type {number}
     * @memberof IngredientWeightsStatus
     */
    noTypicalWeight: number;
    /**
     * Waiting for the background estimator (queued when an estimate is shown).
     * @type {number}
     * @memberof IngredientWeightsStatus
     */
    pending: number;
}

/**
 * Check if a given object implements the IngredientWeightsStatus interface.
 */
export function instanceOfIngredientWeightsStatus(value: object): value is IngredientWeightsStatus {
    if (!('estimated' in value) || value['estimated'] === undefined) return false;
    if (!('failed' in value) || value['failed'] === undefined) return false;
    if (!('failures' in value) || value['failures'] === undefined) return false;
    if (!('noTypicalWeight' in value) || value['noTypicalWeight'] === undefined) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    return true;
}

export function IngredientWeightsStatusFromJSON(json: any): IngredientWeightsStatus {
    return IngredientWeightsStatusFromJSONTyped(json, false);
}

export function IngredientWeightsStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): IngredientWeightsStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'estimated': json['estimated'],
        'failed': json['failed'],
        'failures': ((json['failures'] as Array<any>).map(IngredientWeightFailureFromJSON)),
        'noTypicalWeight': json['no_typical_weight'],
        'pending': json['pending'],
    };
}

export function IngredientWeightsStatusToJSON(json: any): IngredientWeightsStatus {
    return IngredientWeightsStatusToJSONTyped(json, false);
}

export function IngredientWeightsStatusToJSONTyped(value?: IngredientWeightsStatus | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'estimated': value['estimated'],
        'failed': value['failed'],
        'failures': ((value['failures'] as Array<any>).map(IngredientWeightFailureToJSON)),
        'no_typical_weight': value['noTypicalWeight'],
        'pending': value['pending'],
    };
}

