/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Ingredient
 */
export interface Ingredient {
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    amount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    item: string;
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    note?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Ingredient
     */
    unit?: string | null;
}

/**
 * Check if a given object implements the Ingredient interface.
 */
export function instanceOfIngredient(value: object): value is Ingredient {
    if (!('item' in value) || value['item'] === undefined) return false;
    return true;
}

export function IngredientFromJSON(json: any): Ingredient {
    return IngredientFromJSONTyped(json, false);
}

export function IngredientFromJSONTyped(json: any, ignoreDiscriminator: boolean): Ingredient {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'item': json['item'],
        'note': json['note'] == null ? undefined : json['note'],
        'unit': json['unit'] == null ? undefined : json['unit'],
    };
}

export function IngredientToJSON(json: any): Ingredient {
    return IngredientToJSONTyped(json, false);
}

export function IngredientToJSONTyped(value?: Ingredient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'item': value['item'],
        'note': value['note'],
        'unit': value['unit'],
    };
}

