/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PhotoSummary } from './PhotoSummary';
import {
    PhotoSummaryFromJSON,
    PhotoSummaryFromJSONTyped,
    PhotoSummaryToJSON,
    PhotoSummaryToJSONTyped,
} from './PhotoSummary';

/**
 * 
 * @export
 * @interface ListPhotosResponse
 */
export interface ListPhotosResponse {
    /**
     * 
     * @type {Array<PhotoSummary>}
     * @memberof ListPhotosResponse
     */
    photos: Array<PhotoSummary>;
}

/**
 * Check if a given object implements the ListPhotosResponse interface.
 */
export function instanceOfListPhotosResponse(value: object): value is ListPhotosResponse {
    if (!('photos' in value) || value['photos'] === undefined) return false;
    return true;
}

export function ListPhotosResponseFromJSON(json: any): ListPhotosResponse {
    return ListPhotosResponseFromJSONTyped(json, false);
}

export function ListPhotosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListPhotosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'photos': ((json['photos'] as Array<any>).map(PhotoSummaryFromJSON)),
    };
}

export function ListPhotosResponseToJSON(json: any): ListPhotosResponse {
    return ListPhotosResponseToJSONTyped(json, false);
}

export function ListPhotosResponseToJSONTyped(value?: ListPhotosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'photos': ((value['photos'] as Array<any>).map(PhotoSummaryToJSON)),
    };
}

