/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for looking up import jobs by idempotency key
 * @export
 * @interface LookupImportJobsRequest
 */
export interface LookupImportJobsRequest {
    /**
     * Keys previously sent as ImportRecipeRequest.idempotency_key (at most 1000)
     * @type {Array<string>}
     * @memberof LookupImportJobsRequest
     */
    idempotencyKeys: Array<string>;
}

/**
 * Check if a given object implements the LookupImportJobsRequest interface.
 */
export function instanceOfLookupImportJobsRequest(value: object): value is LookupImportJobsRequest {
    if (!('idempotencyKeys' in value) || value['idempotencyKeys'] === undefined) return false;
    return true;
}

export function LookupImportJobsRequestFromJSON(json: any): LookupImportJobsRequest {
    return LookupImportJobsRequestFromJSONTyped(json, false);
}

export function LookupImportJobsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupImportJobsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'idempotencyKeys': json['idempotency_keys'],
    };
}

export function LookupImportJobsRequestToJSON(json: any): LookupImportJobsRequest {
    return LookupImportJobsRequestToJSONTyped(json, false);
}

export function LookupImportJobsRequestToJSONTyped(value?: LookupImportJobsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'idempotency_keys': value['idempotencyKeys'],
    };
}

