/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ImportJobKey } from './ImportJobKey';
import {
    ImportJobKeyFromJSON,
    ImportJobKeyFromJSONTyped,
    ImportJobKeyToJSON,
    ImportJobKeyToJSONTyped,
} from './ImportJobKey';

/**
 * The caller's import jobs for the requested keys; unknown keys are omitted
 * @export
 * @interface LookupImportJobsResponse
 */
export interface LookupImportJobsResponse {
    /**
     * 
     * @type {Array<ImportJobKey>}
     * @memberof LookupImportJobsResponse
     */
    jobs: Array<ImportJobKey>;
}

/**
 * Check if a given object implements the LookupImportJobsResponse interface.
 */
export function instanceOfLookupImportJobsResponse(value: object): value is LookupImportJobsResponse {
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    return true;
}

export function LookupImportJobsResponseFromJSON(json: any): LookupImportJobsResponse {
    return LookupImportJobsResponseFromJSONTyped(json, false);
}

export function LookupImportJobsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LookupImportJobsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobs': ((json['jobs'] as Array<any>).map(ImportJobKeyFromJSON)),
    };
}

export function LookupImportJobsResponseToJSON(json: any): LookupImportJobsResponse {
    return LookupImportJobsResponseToJSONTyped(json, false);
}

export function LookupImportJobsResponseToJSONTyped(value?: LookupImportJobsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jobs': ((value['jobs'] as Array<any>).map(ImportJobKeyToJSON)),
    };
}

