/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NormalizeTitleResponse
 */
export interface NormalizeTitleResponse {
    /**
     * 
     * @type {boolean}
     * @memberof NormalizeTitleResponse
     */
    cached: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof NormalizeTitleResponse
     */
    changed: boolean;
    /**
     * 
     * @type {string}
     * @memberof NormalizeTitleResponse
     */
    normalizedTitle: string;
    /**
     * 
     * @type {string}
     * @memberof NormalizeTitleResponse
     */
    originalTitle: string;
}

/**
 * Check if a given object implements the NormalizeTitleResponse interface.
 */
export function instanceOfNormalizeTitleResponse(value: object): value is NormalizeTitleResponse {
    if (!('cached' in value) || value['cached'] === undefined) return false;
    if (!('changed' in value) || value['changed'] === undefined) return false;
    if (!('normalizedTitle' in value) || value['normalizedTitle'] === undefined) return false;
    if (!('originalTitle' in value) || value['originalTitle'] === undefined) return false;
    return true;
}

export function NormalizeTitleResponseFromJSON(json: any): NormalizeTitleResponse {
    return NormalizeTitleResponseFromJSONTyped(json, false);
}

export function NormalizeTitleResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NormalizeTitleResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cached': json['cached'],
        'changed': json['changed'],
        'normalizedTitle': json['normalized_title'],
        'originalTitle': json['original_title'],
    };
}

export function NormalizeTitleResponseToJSON(json: any): NormalizeTitleResponse {
    return NormalizeTitleResponseToJSONTyped(json, false);
}

export function NormalizeTitleResponseToJSONTyped(value?: NormalizeTitleResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cached': value['cached'],
        'changed': value['changed'],
        'normalized_title': value['normalizedTitle'],
        'original_title': value['originalTitle'],
    };
}

