/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginationMetadata
 */
export interface PaginationMetadata {
    /**
     * Number of items requested (limit)
     * @type {number}
     * @memberof PaginationMetadata
     */
    limit: number;
    /**
     * Number of items skipped (offset)
     * @type {number}
     * @memberof PaginationMetadata
     */
    offset: number;
    /**
     * Total number of items available
     * @type {number}
     * @memberof PaginationMetadata
     */
    total: number;
}

/**
 * Check if a given object implements the PaginationMetadata interface.
 */
export function instanceOfPaginationMetadata(value: object): value is PaginationMetadata {
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PaginationMetadataFromJSON(json: any): PaginationMetadata {
    return PaginationMetadataFromJSONTyped(json, false);
}

export function PaginationMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginationMetadata {
    if (json == null) {
        return json;
    }
    return {
        
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function PaginationMetadataToJSON(json: any): PaginationMetadata {
    return PaginationMetadataToJSONTyped(json, false);
}

export function PaginationMetadataToJSONTyped(value?: PaginationMetadata | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

