/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrepareTextRecipeRequest
 */
export interface PrepareTextRecipeRequest {
    /**
     * A whole recipe, typed or pasted as unstructured text.
     * @type {string}
     * @memberof PrepareTextRecipeRequest
     */
    text: string;
}

/**
 * Check if a given object implements the PrepareTextRecipeRequest interface.
 */
export function instanceOfPrepareTextRecipeRequest(value: object): value is PrepareTextRecipeRequest {
    if (!('text' in value) || value['text'] === undefined) return false;
    return true;
}

export function PrepareTextRecipeRequestFromJSON(json: any): PrepareTextRecipeRequest {
    return PrepareTextRecipeRequestFromJSONTyped(json, false);
}

export function PrepareTextRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareTextRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'text': json['text'],
    };
}

export function PrepareTextRecipeRequestToJSON(json: any): PrepareTextRecipeRequest {
    return PrepareTextRecipeRequestToJSONTyped(json, false);
}

export function PrepareTextRecipeRequestToJSONTyped(value?: PrepareTextRecipeRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text': value['text'],
    };
}

