/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DerivedMeasurement } from './DerivedMeasurement';
import {
    DerivedMeasurementFromJSON,
    DerivedMeasurementFromJSONTyped,
    DerivedMeasurementToJSON,
    DerivedMeasurementToJSONTyped,
} from './DerivedMeasurement';
import type { RecipeContent } from './RecipeContent';
import {
    RecipeContentFromJSON,
    RecipeContentFromJSONTyped,
    RecipeContentToJSON,
    RecipeContentToJSONTyped,
} from './RecipeContent';

/**
 * 
 * @export
 * @interface PrepareTextRecipeResponse
 */
export interface PrepareTextRecipeResponse {
    /**
     * 
     * @type {RecipeContent}
     * @memberof PrepareTextRecipeResponse
     */
    content: RecipeContent;
    /**
     * Approximate grams for `content.ingredients` that have them, for
     * previewing the draft. Never saved.
     * @type {Array<DerivedMeasurement>}
     * @memberof PrepareTextRecipeResponse
     */
    derivedMeasurements: Array<DerivedMeasurement>;
    /**
     * Editable ingredient lines. Send these as raw_ingredients when saving.
     * @type {string}
     * @memberof PrepareTextRecipeResponse
     */
    rawIngredients: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PrepareTextRecipeResponse
     */
    warnings: Array<string>;
}

/**
 * Check if a given object implements the PrepareTextRecipeResponse interface.
 */
export function instanceOfPrepareTextRecipeResponse(value: object): value is PrepareTextRecipeResponse {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('derivedMeasurements' in value) || value['derivedMeasurements'] === undefined) return false;
    if (!('rawIngredients' in value) || value['rawIngredients'] === undefined) return false;
    if (!('warnings' in value) || value['warnings'] === undefined) return false;
    return true;
}

export function PrepareTextRecipeResponseFromJSON(json: any): PrepareTextRecipeResponse {
    return PrepareTextRecipeResponseFromJSONTyped(json, false);
}

export function PrepareTextRecipeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrepareTextRecipeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'content': RecipeContentFromJSON(json['content']),
        'derivedMeasurements': ((json['derived_measurements'] as Array<any>).map(DerivedMeasurementFromJSON)),
        'rawIngredients': json['raw_ingredients'],
        'warnings': json['warnings'],
    };
}

export function PrepareTextRecipeResponseToJSON(json: any): PrepareTextRecipeResponse {
    return PrepareTextRecipeResponseToJSONTyped(json, false);
}

export function PrepareTextRecipeResponseToJSONTyped(value?: PrepareTextRecipeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'content': RecipeContentToJSON(value['content']),
        'derived_measurements': ((value['derivedMeasurements'] as Array<any>).map(DerivedMeasurementToJSON)),
        'raw_ingredients': value['rawIngredients'],
        'warnings': value['warnings'],
    };
}

