/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ingredient } from './Ingredient';
import {
    IngredientFromJSON,
    IngredientFromJSONTyped,
    IngredientToJSON,
    IngredientToJSONTyped,
} from './Ingredient';

/**
 * Core recipe content - all fields that can be enriched by AI.
 * Used for enrichment APIs and recipe import.
 * @export
 * @interface RecipeContent
 */
export interface RecipeContent {
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    cookTime?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    difficulty?: string | null;
    /**
     * 
     * @type {Array<Ingredient>}
     * @memberof RecipeContent
     */
    ingredients: Array<Ingredient>;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    instructions: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    nutritionalInfo?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    prepTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeContent
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    servings?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    sourceName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    sourceUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeContent
     */
    tags?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeContent
     */
    totalTime?: string | null;
}

/**
 * Check if a given object implements the RecipeContent interface.
 */
export function instanceOfRecipeContent(value: object): value is RecipeContent {
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function RecipeContentFromJSON(json: any): RecipeContent {
    return RecipeContentFromJSONTyped(json, false);
}

export function RecipeContentFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeContent {
    if (json == null) {
        return json;
    }
    return {
        
        'cookTime': json['cook_time'] == null ? undefined : json['cook_time'],
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientFromJSON)),
        'instructions': json['instructions'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'nutritionalInfo': json['nutritional_info'] == null ? undefined : json['nutritional_info'],
        'prepTime': json['prep_time'] == null ? undefined : json['prep_time'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'servings': json['servings'] == null ? undefined : json['servings'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'sourceUrl': json['source_url'] == null ? undefined : json['source_url'],
        'tags': json['tags'] == null ? undefined : json['tags'],
        'title': json['title'],
        'totalTime': json['total_time'] == null ? undefined : json['total_time'],
    };
}

export function RecipeContentToJSON(json: any): RecipeContent {
    return RecipeContentToJSONTyped(json, false);
}

export function RecipeContentToJSONTyped(value?: RecipeContent | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cook_time': value['cookTime'],
        'description': value['description'],
        'difficulty': value['difficulty'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientToJSON)),
        'instructions': value['instructions'],
        'notes': value['notes'],
        'nutritional_info': value['nutritionalInfo'],
        'prep_time': value['prepTime'],
        'rating': value['rating'],
        'servings': value['servings'],
        'source_name': value['sourceName'],
        'source_url': value['sourceUrl'],
        'tags': value['tags'],
        'title': value['title'],
        'total_time': value['totalTime'],
    };
}

