/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ingredient } from './Ingredient';
import {
    IngredientFromJSON,
    IngredientFromJSONTyped,
    IngredientToJSON,
    IngredientToJSONTyped,
} from './Ingredient';

/**
 * 
 * @export
 * @interface RecipeResponse
 */
export interface RecipeResponse {
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    cookTime?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RecipeResponse
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    difficulty?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    id: string;
    /**
     * 
     * @type {Array<Ingredient>}
     * @memberof RecipeResponse
     */
    ingredients: Array<Ingredient>;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    instructions: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    notes?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    nutritionalInfo?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeResponse
     */
    photoIds: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    prepTime?: string | null;
    /**
     * 
     * @type {number}
     * @memberof RecipeResponse
     */
    rating?: number | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    servings?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    sourceName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    sourceUrl?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof RecipeResponse
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeResponse
     */
    totalTime?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof RecipeResponse
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the RecipeResponse interface.
 */
export function instanceOfRecipeResponse(value: object): value is RecipeResponse {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('photoIds' in value) || value['photoIds'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function RecipeResponseFromJSON(json: any): RecipeResponse {
    return RecipeResponseFromJSONTyped(json, false);
}

export function RecipeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'cookTime': json['cook_time'] == null ? undefined : json['cook_time'],
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'difficulty': json['difficulty'] == null ? undefined : json['difficulty'],
        'id': json['id'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientFromJSON)),
        'instructions': json['instructions'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'nutritionalInfo': json['nutritional_info'] == null ? undefined : json['nutritional_info'],
        'photoIds': json['photo_ids'],
        'prepTime': json['prep_time'] == null ? undefined : json['prep_time'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'servings': json['servings'] == null ? undefined : json['servings'],
        'sourceName': json['source_name'] == null ? undefined : json['source_name'],
        'sourceUrl': json['source_url'] == null ? undefined : json['source_url'],
        'tags': json['tags'],
        'title': json['title'],
        'totalTime': json['total_time'] == null ? undefined : json['total_time'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function RecipeResponseToJSON(json: any): RecipeResponse {
    return RecipeResponseToJSONTyped(json, false);
}

export function RecipeResponseToJSONTyped(value?: RecipeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cook_time': value['cookTime'],
        'created_at': value['createdAt'].toISOString(),
        'description': value['description'],
        'difficulty': value['difficulty'],
        'id': value['id'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientToJSON)),
        'instructions': value['instructions'],
        'notes': value['notes'],
        'nutritional_info': value['nutritionalInfo'],
        'photo_ids': value['photoIds'],
        'prep_time': value['prepTime'],
        'rating': value['rating'],
        'servings': value['servings'],
        'source_name': value['sourceName'],
        'source_url': value['sourceUrl'],
        'tags': value['tags'],
        'title': value['title'],
        'total_time': value['totalTime'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

