/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameTagResponse
 */
export interface RenameTagResponse {
    /**
     * 
     * @type {string}
     * @memberof RenameTagResponse
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof RenameTagResponse
     */
    name: string;
}

/**
 * Check if a given object implements the RenameTagResponse interface.
 */
export function instanceOfRenameTagResponse(value: object): value is RenameTagResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function RenameTagResponseFromJSON(json: any): RenameTagResponse {
    return RenameTagResponseFromJSONTyped(json, false);
}

export function RenameTagResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameTagResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function RenameTagResponseToJSON(json: any): RenameTagResponse {
    return RenameTagResponseToJSONTyped(json, false);
}

export function RenameTagResponseToJSONTyped(value?: RenameTagResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

