/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReparseIngredientsResponse
 */
export interface ReparseIngredientsResponse {
    /**
     * Ingredient lines whose item changed.
     * @type {number}
     * @memberof ReparseIngredientsResponse
     */
    ingredientsChanged: number;
    /**
     * Recipes whose current version was checked.
     * @type {number}
     * @memberof ReparseIngredientsResponse
     */
    recipesChecked: number;
    /**
     * Recipes that got a new version because an ingredient changed.
     * @type {number}
     * @memberof ReparseIngredientsResponse
     */
    recipesUpdated: number;
}

/**
 * Check if a given object implements the ReparseIngredientsResponse interface.
 */
export function instanceOfReparseIngredientsResponse(value: object): value is ReparseIngredientsResponse {
    if (!('ingredientsChanged' in value) || value['ingredientsChanged'] === undefined) return false;
    if (!('recipesChecked' in value) || value['recipesChecked'] === undefined) return false;
    if (!('recipesUpdated' in value) || value['recipesUpdated'] === undefined) return false;
    return true;
}

export function ReparseIngredientsResponseFromJSON(json: any): ReparseIngredientsResponse {
    return ReparseIngredientsResponseFromJSONTyped(json, false);
}

export function ReparseIngredientsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReparseIngredientsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'ingredientsChanged': json['ingredients_changed'],
        'recipesChecked': json['recipes_checked'],
        'recipesUpdated': json['recipes_updated'],
    };
}

export function ReparseIngredientsResponseToJSON(json: any): ReparseIngredientsResponse {
    return ReparseIngredientsResponseToJSONTyped(json, false);
}

export function ReparseIngredientsResponseToJSONTyped(value?: ReparseIngredientsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'ingredients_changed': value['ingredientsChanged'],
        'recipes_checked': value['recipesChecked'],
        'recipes_updated': value['recipesUpdated'],
    };
}

