/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RescrapeResponse
 */
export interface RescrapeResponse {
    /**
     * The scrape job ID
     * @type {string}
     * @memberof RescrapeResponse
     */
    jobId: string;
    /**
     * Current job status
     * @type {string}
     * @memberof RescrapeResponse
     */
    status: string;
}

/**
 * Check if a given object implements the RescrapeResponse interface.
 */
export function instanceOfRescrapeResponse(value: object): value is RescrapeResponse {
    if (!('jobId' in value) || value['jobId'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RescrapeResponseFromJSON(json: any): RescrapeResponse {
    return RescrapeResponseFromJSONTyped(json, false);
}

export function RescrapeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RescrapeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'jobId': json['job_id'],
        'status': json['status'],
    };
}

export function RescrapeResponseToJSON(json: any): RescrapeResponse {
    return RescrapeResponseToJSONTyped(json, false);
}

export function RescrapeResponseToJSONTyped(value?: RescrapeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'job_id': value['jobId'],
        'status': value['status'],
    };
}

