/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RetryScrapeResponse
 */
export interface RetryScrapeResponse {
    /**
     * The scrape job ID
     * @type {string}
     * @memberof RetryScrapeResponse
     */
    id: string;
    /**
     * New job status after retry
     * @type {string}
     * @memberof RetryScrapeResponse
     */
    status: string;
}

/**
 * Check if a given object implements the RetryScrapeResponse interface.
 */
export function instanceOfRetryScrapeResponse(value: object): value is RetryScrapeResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function RetryScrapeResponseFromJSON(json: any): RetryScrapeResponse {
    return RetryScrapeResponseFromJSONTyped(json, false);
}

export function RetryScrapeResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RetryScrapeResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': json['status'],
    };
}

export function RetryScrapeResponseToJSON(json: any): RetryScrapeResponse {
    return RetryScrapeResponseToJSONTyped(json, false);
}

export function RetryScrapeResponseToJSONTyped(value?: RetryScrapeResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'status': value['status'],
    };
}

