/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShoppingListItemResponse
 */
export interface ShoppingListItemResponse {
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    amount?: string | null;
    /**
     * Computed aisle category for grouping (e.g., "Produce", "Dairy & Eggs")
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    category: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof ShoppingListItemResponse
     */
    isChecked: boolean;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    item: string;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListItemResponse
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    sourceRecipeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ShoppingListItemResponse
     */
    sourceRecipeTitle?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ShoppingListItemResponse
     */
    updatedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof ShoppingListItemResponse
     */
    version: number;
}

/**
 * Check if a given object implements the ShoppingListItemResponse interface.
 */
export function instanceOfShoppingListItemResponse(value: object): value is ShoppingListItemResponse {
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isChecked' in value) || value['isChecked'] === undefined) return false;
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function ShoppingListItemResponseFromJSON(json: any): ShoppingListItemResponse {
    return ShoppingListItemResponseFromJSONTyped(json, false);
}

export function ShoppingListItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingListItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'category': json['category'],
        'id': json['id'],
        'isChecked': json['is_checked'],
        'item': json['item'],
        'note': json['note'] == null ? undefined : json['note'],
        'sortOrder': json['sort_order'],
        'sourceRecipeId': json['source_recipe_id'] == null ? undefined : json['source_recipe_id'],
        'sourceRecipeTitle': json['source_recipe_title'] == null ? undefined : json['source_recipe_title'],
        'updatedAt': (new Date(json['updated_at'])),
        'version': json['version'],
    };
}

export function ShoppingListItemResponseToJSON(json: any): ShoppingListItemResponse {
    return ShoppingListItemResponseToJSONTyped(json, false);
}

export function ShoppingListItemResponseToJSONTyped(value?: ShoppingListItemResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'category': value['category'],
        'id': value['id'],
        'is_checked': value['isChecked'],
        'item': value['item'],
        'note': value['note'],
        'sort_order': value['sortOrder'],
        'source_recipe_id': value['sourceRecipeId'],
        'source_recipe_title': value['sourceRecipeTitle'],
        'updated_at': value['updatedAt'].toISOString(),
        'version': value['version'],
    };
}

