/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShoppingListItemResponse } from './ShoppingListItemResponse';
import {
    ShoppingListItemResponseFromJSON,
    ShoppingListItemResponseFromJSONTyped,
    ShoppingListItemResponseToJSON,
    ShoppingListItemResponseToJSONTyped,
} from './ShoppingListItemResponse';

/**
 * 
 * @export
 * @interface ShoppingListResponse
 */
export interface ShoppingListResponse {
    /**
     * 
     * @type {Array<ShoppingListItemResponse>}
     * @memberof ShoppingListResponse
     */
    items: Array<ShoppingListItemResponse>;
}

/**
 * Check if a given object implements the ShoppingListResponse interface.
 */
export function instanceOfShoppingListResponse(value: object): value is ShoppingListResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function ShoppingListResponseFromJSON(json: any): ShoppingListResponse {
    return ShoppingListResponseFromJSONTyped(json, false);
}

export function ShoppingListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ShoppingListItemResponseFromJSON)),
    };
}

export function ShoppingListResponseToJSON(json: any): ShoppingListResponse {
    return ShoppingListResponseToJSONTyped(json, false);
}

export function ShoppingListResponseToJSONTyped(value?: ShoppingListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ShoppingListItemResponseToJSON)),
    };
}

