/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface SignupResponse
 */
export interface SignupResponse {
  /**
   *
   * @type {string}
   * @memberof SignupResponse
   */
  token: string;
  /**
   *
   * @type {string}
   * @memberof SignupResponse
   */
  userId: string;
}

/**
 * Check if a given object implements the SignupResponse interface.
 */
export function instanceOfSignupResponse(
  value: object,
): value is SignupResponse {
  if (!("token" in value) || value["token"] === undefined) return false;
  if (!("userId" in value) || value["userId"] === undefined) return false;
  return true;
}

export function SignupResponseFromJSON(json: any): SignupResponse {
  return SignupResponseFromJSONTyped(json, false);
}

export function SignupResponseFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignupResponse {
  if (json == null) {
    return json;
  }
  return {
    token: json["token"],
    userId: json["user_id"],
  };
}

export function SignupResponseToJSON(json: any): SignupResponse {
  return SignupResponseToJSONTyped(json, false);
}

export function SignupResponseToJSONTyped(
  value?: SignupResponse | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    token: value["token"],
    user_id: value["userId"],
  };
}
