/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sort field for recipe list
 * @export
 */
export const SortBy = {
    UpdatedAt: 'updated_at',
    Random: 'random'
} as const;
export type SortBy = typeof SortBy[keyof typeof SortBy];


export function instanceOfSortBy(value: any): boolean {
    for (const key in SortBy) {
        if (Object.prototype.hasOwnProperty.call(SortBy, key)) {
            if (SortBy[key as keyof typeof SortBy] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SortByFromJSON(json: any): SortBy {
    return SortByFromJSONTyped(json, false);
}

export function SortByFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortBy {
    return json as SortBy;
}

export function SortByToJSON(value?: SortBy | null): any {
    return value as any;
}

export function SortByToJSONTyped(value: any, ignoreDiscriminator: boolean): SortBy {
    return value as SortBy;
}

