/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A single pipeline step's state for the status API response.
 * @export
 * @interface StepState
 */
export interface StepState {
    /**
     * 
     * @type {number}
     * @memberof StepState
     */
    durationMs?: number | null;
    /**
     * 
     * @type {string}
     * @memberof StepState
     */
    error?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof StepState
     */
    finishedAt?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof StepState
     */
    hasOutput: boolean;
    /**
     * 
     * @type {string}
     * @memberof StepState
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof StepState
     */
    startedAt?: Date | null;
    /**
     * One of "pending", "running", "completed", "failed", "skipped".
     * @type {string}
     * @memberof StepState
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof StepState
     */
    summary?: string | null;
}

/**
 * Check if a given object implements the StepState interface.
 */
export function instanceOfStepState(value: object): value is StepState {
    if (!('hasOutput' in value) || value['hasOutput'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function StepStateFromJSON(json: any): StepState {
    return StepStateFromJSONTyped(json, false);
}

export function StepStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): StepState {
    if (json == null) {
        return json;
    }
    return {
        
        'durationMs': json['duration_ms'] == null ? undefined : json['duration_ms'],
        'error': json['error'] == null ? undefined : json['error'],
        'finishedAt': json['finished_at'] == null ? undefined : (new Date(json['finished_at'])),
        'hasOutput': json['has_output'],
        'name': json['name'],
        'startedAt': json['started_at'] == null ? undefined : (new Date(json['started_at'])),
        'status': json['status'],
        'summary': json['summary'] == null ? undefined : json['summary'],
    };
}

export function StepStateToJSON(json: any): StepState {
    return StepStateToJSONTyped(json, false);
}

export function StepStateToJSONTyped(value?: StepState | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'duration_ms': value['durationMs'],
        'error': value['error'],
        'finished_at': value['finishedAt'] == null ? value['finishedAt'] : value['finishedAt'].toISOString(),
        'has_output': value['hasOutput'],
        'name': value['name'],
        'started_at': value['startedAt'] == null ? value['startedAt'] : value['startedAt'].toISOString(),
        'status': value['status'],
        'summary': value['summary'],
    };
}

