/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncUpdatedItem
 */
export interface SyncUpdatedItem {
    /**
     * 
     * @type {string}
     * @memberof SyncUpdatedItem
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof SyncUpdatedItem
     */
    success: boolean;
    /**
     * 
     * @type {number}
     * @memberof SyncUpdatedItem
     */
    version: number;
}

/**
 * Check if a given object implements the SyncUpdatedItem interface.
 */
export function instanceOfSyncUpdatedItem(value: object): value is SyncUpdatedItem {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function SyncUpdatedItemFromJSON(json: any): SyncUpdatedItem {
    return SyncUpdatedItemFromJSONTyped(json, false);
}

export function SyncUpdatedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncUpdatedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'success': json['success'],
        'version': json['version'],
    };
}

export function SyncUpdatedItemToJSON(json: any): SyncUpdatedItem {
    return SyncUpdatedItemToJSONTyped(json, false);
}

export function SyncUpdatedItemToJSONTyped(value?: SyncUpdatedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'success': value['success'],
        'version': value['version'],
    };
}

