/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SyncCreatedItem
 */
export interface SyncCreatedItem {
    /**
     * 
     * @type {string}
     * @memberof SyncCreatedItem
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof SyncCreatedItem
     */
    serverId: string;
    /**
     * 
     * @type {number}
     * @memberof SyncCreatedItem
     */
    version: number;
}

/**
 * Check if a given object implements the SyncCreatedItem interface.
 */
export function instanceOfSyncCreatedItem(value: object): value is SyncCreatedItem {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('serverId' in value) || value['serverId'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function SyncCreatedItemFromJSON(json: any): SyncCreatedItem {
    return SyncCreatedItemFromJSONTyped(json, false);
}

export function SyncCreatedItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncCreatedItem {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'serverId': json['server_id'],
        'version': json['version'],
    };
}

export function SyncCreatedItemToJSON(json: any): SyncCreatedItem {
    return SyncCreatedItemToJSONTyped(json, false);
}

export function SyncCreatedItemToJSONTyped(value?: SyncCreatedItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'server_id': value['serverId'],
        'version': value['version'],
    };
}

