/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to create an item during sync (created offline)
 * @export
 * @interface SyncCreateItem
 */
export interface SyncCreateItem {
    /**
     * 
     * @type {string}
     * @memberof SyncCreateItem
     */
    amount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncCreateItem
     */
    clientId: string;
    /**
     * 
     * @type {boolean}
     * @memberof SyncCreateItem
     */
    isChecked: boolean;
    /**
     * 
     * @type {string}
     * @memberof SyncCreateItem
     */
    item: string;
    /**
     * 
     * @type {string}
     * @memberof SyncCreateItem
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SyncCreateItem
     */
    sortOrder: number;
    /**
     * 
     * @type {string}
     * @memberof SyncCreateItem
     */
    sourceRecipeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncCreateItem
     */
    sourceRecipeTitle?: string | null;
}

/**
 * Check if a given object implements the SyncCreateItem interface.
 */
export function instanceOfSyncCreateItem(value: object): value is SyncCreateItem {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('isChecked' in value) || value['isChecked'] === undefined) return false;
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    return true;
}

export function SyncCreateItemFromJSON(json: any): SyncCreateItem {
    return SyncCreateItemFromJSONTyped(json, false);
}

export function SyncCreateItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncCreateItem {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'clientId': json['client_id'],
        'isChecked': json['is_checked'],
        'item': json['item'],
        'note': json['note'] == null ? undefined : json['note'],
        'sortOrder': json['sort_order'],
        'sourceRecipeId': json['source_recipe_id'] == null ? undefined : json['source_recipe_id'],
        'sourceRecipeTitle': json['source_recipe_title'] == null ? undefined : json['source_recipe_title'],
    };
}

export function SyncCreateItemToJSON(json: any): SyncCreateItem {
    return SyncCreateItemToJSONTyped(json, false);
}

export function SyncCreateItemToJSONTyped(value?: SyncCreateItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'client_id': value['clientId'],
        'is_checked': value['isChecked'],
        'item': value['item'],
        'note': value['note'],
        'sort_order': value['sortOrder'],
        'source_recipe_id': value['sourceRecipeId'],
        'source_recipe_title': value['sourceRecipeTitle'],
    };
}

