/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Ingredient } from './Ingredient';
import {
    IngredientFromJSON,
    IngredientFromJSONTyped,
    IngredientToJSON,
    IngredientToJSONTyped,
} from './Ingredient';

/**
 * Read-only recipe data needed to populate the iOS cache and mirror server search.
 * @export
 * @interface SyncRecipe
 */
export interface SyncRecipe {
    /**
     * 
     * @type {Date}
     * @memberof SyncRecipe
     */
    createdAt: Date;
    /**
     * 
     * @type {string}
     * @memberof SyncRecipe
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncRecipe
     */
    id: string;
    /**
     * 
     * @type {Array<Ingredient>}
     * @memberof SyncRecipe
     */
    ingredients: Array<Ingredient>;
    /**
     * 
     * @type {string}
     * @memberof SyncRecipe
     */
    instructions: string;
    /**
     * 
     * @type {string}
     * @memberof SyncRecipe
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SyncRecipe
     */
    rating?: number | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof SyncRecipe
     */
    tags: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SyncRecipe
     */
    thumbnailPhotoId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncRecipe
     */
    title: string;
    /**
     * 
     * @type {Date}
     * @memberof SyncRecipe
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the SyncRecipe interface.
 */
export function instanceOfSyncRecipe(value: object): value is SyncRecipe {
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('ingredients' in value) || value['ingredients'] === undefined) return false;
    if (!('instructions' in value) || value['instructions'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function SyncRecipeFromJSON(json: any): SyncRecipe {
    return SyncRecipeFromJSONTyped(json, false);
}

export function SyncRecipeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncRecipe {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (new Date(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'ingredients': ((json['ingredients'] as Array<any>).map(IngredientFromJSON)),
        'instructions': json['instructions'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'tags': json['tags'],
        'thumbnailPhotoId': json['thumbnail_photo_id'] == null ? undefined : json['thumbnail_photo_id'],
        'title': json['title'],
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function SyncRecipeToJSON(json: any): SyncRecipe {
    return SyncRecipeToJSONTyped(json, false);
}

export function SyncRecipeToJSONTyped(value?: SyncRecipe | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'].toISOString(),
        'description': value['description'],
        'id': value['id'],
        'ingredients': ((value['ingredients'] as Array<any>).map(IngredientToJSON)),
        'instructions': value['instructions'],
        'notes': value['notes'],
        'rating': value['rating'],
        'tags': value['tags'],
        'thumbnail_photo_id': value['thumbnailPhotoId'],
        'title': value['title'],
        'updated_at': value['updatedAt'].toISOString(),
    };
}

