/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request to update an item during sync (modified offline)
 * @export
 * @interface SyncUpdateItem
 */
export interface SyncUpdateItem {
    /**
     * 
     * @type {string}
     * @memberof SyncUpdateItem
     */
    amount?: string | null;
    /**
     * Expected version for optimistic locking
     * @type {number}
     * @memberof SyncUpdateItem
     */
    expectedVersion: number;
    /**
     * 
     * @type {string}
     * @memberof SyncUpdateItem
     */
    id: string;
    /**
     * 
     * @type {boolean}
     * @memberof SyncUpdateItem
     */
    isChecked?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof SyncUpdateItem
     */
    item?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SyncUpdateItem
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SyncUpdateItem
     */
    sortOrder?: number | null;
}

/**
 * Check if a given object implements the SyncUpdateItem interface.
 */
export function instanceOfSyncUpdateItem(value: object): value is SyncUpdateItem {
    if (!('expectedVersion' in value) || value['expectedVersion'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function SyncUpdateItemFromJSON(json: any): SyncUpdateItem {
    return SyncUpdateItemFromJSONTyped(json, false);
}

export function SyncUpdateItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SyncUpdateItem {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'expectedVersion': json['expected_version'],
        'id': json['id'],
        'isChecked': json['is_checked'] == null ? undefined : json['is_checked'],
        'item': json['item'] == null ? undefined : json['item'],
        'note': json['note'] == null ? undefined : json['note'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function SyncUpdateItemToJSON(json: any): SyncUpdateItem {
    return SyncUpdateItemToJSONTyped(json, false);
}

export function SyncUpdateItemToJSONTyped(value?: SyncUpdateItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'expected_version': value['expectedVersion'],
        'id': value['id'],
        'is_checked': value['isChecked'],
        'item': value['item'],
        'note': value['note'],
        'sort_order': value['sortOrder'],
    };
}

