/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TagsResponse
 */
export interface TagsResponse {
    /**
     * List of distinct tags used across user's recipes, sorted alphabetically
     * @type {Array<string>}
     * @memberof TagsResponse
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the TagsResponse interface.
 */
export function instanceOfTagsResponse(value: object): value is TagsResponse {
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function TagsResponseFromJSON(json: any): TagsResponse {
    return TagsResponseFromJSONTyped(json, false);
}

export function TagsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'tags': json['tags'],
    };
}

export function TagsResponseToJSON(json: any): TagsResponse {
    return TagsResponseToJSONTyped(json, false);
}

export function TagsResponseToJSONTyped(value?: TagsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'tags': value['tags'],
    };
}

