/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnauthedPingResponse
 */
export interface UnauthedPingResponse {
    /**
     * 
     * @type {string}
     * @memberof UnauthedPingResponse
     */
    message: string;
}

/**
 * Check if a given object implements the UnauthedPingResponse interface.
 */
export function instanceOfUnauthedPingResponse(value: object): value is UnauthedPingResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function UnauthedPingResponseFromJSON(json: any): UnauthedPingResponse {
    return UnauthedPingResponseFromJSONTyped(json, false);
}

export function UnauthedPingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnauthedPingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function UnauthedPingResponseToJSON(json: any): UnauthedPingResponse {
    return UnauthedPingResponseToJSONTyped(json, false);
}

export function UnauthedPingResponseToJSONTyped(value?: UnauthedPingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

