/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UnknownCalorieIngredient
 */
export interface UnknownCalorieIngredient {
    /**
     * 
     * @type {number}
     * @memberof UnknownCalorieIngredient
     */
    index: number;
    /**
     * 
     * @type {string}
     * @memberof UnknownCalorieIngredient
     */
    item: string;
    /**
     * 
     * @type {string}
     * @memberof UnknownCalorieIngredient
     */
    reason: string;
}

/**
 * Check if a given object implements the UnknownCalorieIngredient interface.
 */
export function instanceOfUnknownCalorieIngredient(value: object): value is UnknownCalorieIngredient {
    if (!('index' in value) || value['index'] === undefined) return false;
    if (!('item' in value) || value['item'] === undefined) return false;
    if (!('reason' in value) || value['reason'] === undefined) return false;
    return true;
}

export function UnknownCalorieIngredientFromJSON(json: any): UnknownCalorieIngredient {
    return UnknownCalorieIngredientFromJSONTyped(json, false);
}

export function UnknownCalorieIngredientFromJSONTyped(json: any, ignoreDiscriminator: boolean): UnknownCalorieIngredient {
    if (json == null) {
        return json;
    }
    return {
        
        'index': json['index'],
        'item': json['item'],
        'reason': json['reason'],
    };
}

export function UnknownCalorieIngredientToJSON(json: any): UnknownCalorieIngredient {
    return UnknownCalorieIngredientToJSONTyped(json, false);
}

export function UnknownCalorieIngredientToJSONTyped(value?: UnknownCalorieIngredient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'index': value['index'],
        'item': value['item'],
        'reason': value['reason'],
    };
}

