/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MealType } from './MealType';
import {
    MealTypeFromJSON,
    MealTypeFromJSONTyped,
    MealTypeToJSON,
    MealTypeToJSONTyped,
} from './MealType';

/**
 * 
 * @export
 * @interface UpdateMealPlanRequest
 */
export interface UpdateMealPlanRequest {
    /**
     * 
     * @type {Date}
     * @memberof UpdateMealPlanRequest
     */
    mealDate?: Date | null;
    /**
     * 
     * @type {MealType}
     * @memberof UpdateMealPlanRequest
     */
    mealType?: MealType | null;
    /**
     * Set to empty string to clear notes, or provide new value
     * @type {string}
     * @memberof UpdateMealPlanRequest
     */
    notes?: string | null;
}



/**
 * Check if a given object implements the UpdateMealPlanRequest interface.
 */
export function instanceOfUpdateMealPlanRequest(value: object): value is UpdateMealPlanRequest {
    return true;
}

export function UpdateMealPlanRequestFromJSON(json: any): UpdateMealPlanRequest {
    return UpdateMealPlanRequestFromJSONTyped(json, false);
}

export function UpdateMealPlanRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateMealPlanRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mealDate': json['meal_date'] == null ? undefined : (new Date(json['meal_date'])),
        'mealType': json['meal_type'] == null ? undefined : MealTypeFromJSON(json['meal_type']),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function UpdateMealPlanRequestToJSON(json: any): UpdateMealPlanRequest {
    return UpdateMealPlanRequestToJSONTyped(json, false);
}

export function UpdateMealPlanRequestToJSONTyped(value?: UpdateMealPlanRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'meal_date': value['mealDate'] == null ? value['mealDate'] : value['mealDate'].toISOString().substring(0,10),
        'meal_type': MealTypeToJSON(value['mealType']),
        'notes': value['notes'],
    };
}

