/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateShoppingListItemRequest
 */
export interface UpdateShoppingListItemRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateShoppingListItemRequest
     */
    amount?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateShoppingListItemRequest
     */
    isChecked?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateShoppingListItemRequest
     */
    item?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpdateShoppingListItemRequest
     */
    note?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpdateShoppingListItemRequest
     */
    sortOrder?: number | null;
}

/**
 * Check if a given object implements the UpdateShoppingListItemRequest interface.
 */
export function instanceOfUpdateShoppingListItemRequest(value: object): value is UpdateShoppingListItemRequest {
    return true;
}

export function UpdateShoppingListItemRequestFromJSON(json: any): UpdateShoppingListItemRequest {
    return UpdateShoppingListItemRequestFromJSONTyped(json, false);
}

export function UpdateShoppingListItemRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateShoppingListItemRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'isChecked': json['is_checked'] == null ? undefined : json['is_checked'],
        'item': json['item'] == null ? undefined : json['item'],
        'note': json['note'] == null ? undefined : json['note'],
        'sortOrder': json['sort_order'] == null ? undefined : json['sort_order'],
    };
}

export function UpdateShoppingListItemRequestToJSON(json: any): UpdateShoppingListItemRequest {
    return UpdateShoppingListItemRequestToJSONTyped(json, false);
}

export function UpdateShoppingListItemRequestToJSONTyped(value?: UpdateShoppingListItemRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount': value['amount'],
        'is_checked': value['isChecked'],
        'item': value['item'],
        'note': value['note'],
        'sort_order': value['sortOrder'],
    };
}

