/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadPhotoResponse
 */
export interface UploadPhotoResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadPhotoResponse
     */
    id: string;
}

/**
 * Check if a given object implements the UploadPhotoResponse interface.
 */
export function instanceOfUploadPhotoResponse(value: object): value is UploadPhotoResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    return true;
}

export function UploadPhotoResponseFromJSON(json: any): UploadPhotoResponse {
    return UploadPhotoResponseFromJSONTyped(json, false);
}

export function UploadPhotoResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadPhotoResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function UploadPhotoResponseToJSON(json: any): UploadPhotoResponse {
    return UploadPhotoResponseToJSONTyped(json, false);
}

export function UploadPhotoResponseToJSONTyped(value?: UploadPhotoResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
    };
}

