/* tslint:disable */
/* eslint-disable */
/**
 * ramekin-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VersionSummary } from './VersionSummary';
import {
    VersionSummaryFromJSON,
    VersionSummaryFromJSONTyped,
    VersionSummaryToJSON,
    VersionSummaryToJSONTyped,
} from './VersionSummary';

/**
 * Response for version list endpoint
 * @export
 * @interface VersionListResponse
 */
export interface VersionListResponse {
    /**
     * 
     * @type {Array<VersionSummary>}
     * @memberof VersionListResponse
     */
    versions: Array<VersionSummary>;
}

/**
 * Check if a given object implements the VersionListResponse interface.
 */
export function instanceOfVersionListResponse(value: object): value is VersionListResponse {
    if (!('versions' in value) || value['versions'] === undefined) return false;
    return true;
}

export function VersionListResponseFromJSON(json: any): VersionListResponse {
    return VersionListResponseFromJSONTyped(json, false);
}

export function VersionListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VersionListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'versions': ((json['versions'] as Array<any>).map(VersionSummaryFromJSON)),
    };
}

export function VersionListResponseToJSON(json: any): VersionListResponse {
    return VersionListResponseToJSONTyped(json, false);
}

export function VersionListResponseToJSONTyped(value?: VersionListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versions': ((value['versions'] as Array<any>).map(VersionSummaryToJSON)),
    };
}

