//
// AuthAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class AuthAPI {

    /**

     - parameter loginRequest: (body)  
     - returns: LoginResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func login(loginRequest: LoginRequest) async throws -> LoginResponse {
        return try await loginWithRequestBuilder(loginRequest: loginRequest).execute().body
    }

    /**
     - POST /api/auth/login
     - parameter loginRequest: (body)  
     - returns: RequestBuilder<LoginResponse> 
     */
    open class func loginWithRequestBuilder(loginRequest: LoginRequest) -> RequestBuilder<LoginResponse> {
        let localVariablePath = "/api/auth/login"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: loginRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LoginResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }

    /**

     - parameter signupRequest: (body)  
     - returns: SignupResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func signup(signupRequest: SignupRequest) async throws -> SignupResponse {
        return try await signupWithRequestBuilder(signupRequest: signupRequest).execute().body
    }

    /**
     - POST /api/auth/signup
     - parameter signupRequest: (body)  
     - returns: RequestBuilder<SignupResponse> 
     */
    open class func signupWithRequestBuilder(signupRequest: SignupRequest) -> RequestBuilder<SignupResponse> {
        let localVariablePath = "/api/auth/signup"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: signupRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<SignupResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
