//
// ClientLogsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ClientLogsAPI {

    /**

     - parameter createClientLogRequest: (body)  
     - returns: CreateClientLogResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createClientLog(createClientLogRequest: CreateClientLogRequest) async throws -> CreateClientLogResponse {
        return try await createClientLogWithRequestBuilder(createClientLogRequest: createClientLogRequest).execute().body
    }

    /**
     - POST /api/client-logs
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter createClientLogRequest: (body)  
     - returns: RequestBuilder<CreateClientLogResponse> 
     */
    open class func createClientLogWithRequestBuilder(createClientLogRequest: CreateClientLogRequest) -> RequestBuilder<CreateClientLogResponse> {
        let localVariablePath = "/api/client-logs"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createClientLogRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateClientLogResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Log upload id 
     - returns: GetClientLogResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getClientLog(id: UUID) async throws -> GetClientLogResponse {
        return try await getClientLogWithRequestBuilder(id: id).execute().body
    }

    /**
     - GET /api/client-logs/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Log upload id 
     - returns: RequestBuilder<GetClientLogResponse> 
     */
    open class func getClientLogWithRequestBuilder(id: UUID) -> RequestBuilder<GetClientLogResponse> {
        var localVariablePath = "/api/client-logs/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<GetClientLogResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: ListClientLogsResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listClientLogs() async throws -> ListClientLogsResponse {
        return try await listClientLogsWithRequestBuilder().execute().body
    }

    /**
     - GET /api/client-logs
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - returns: RequestBuilder<ListClientLogsResponse> 
     */
    open class func listClientLogsWithRequestBuilder() -> RequestBuilder<ListClientLogsResponse> {
        let localVariablePath = "/api/client-logs"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ListClientLogsResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
