//
// EnrichAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class EnrichAPI {

    /**
     Enrich a recipe using AI
     
     - parameter recipeContent: (body)  
     - returns: RecipeContent
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func enrichRecipe(recipeContent: RecipeContent) async throws -> RecipeContent {
        return try await enrichRecipeWithRequestBuilder(recipeContent: recipeContent).execute().body
    }

    /**
     Enrich a recipe using AI
     - POST /api/enrich
     - This is a stateless endpoint that takes a recipe object and returns an enriched version. It does NOT modify any database records. The client can apply the enriched data via a normal PUT /api/recipes/{id} call.  Currently enriches tags by suggesting from the user's existing tag library.
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter recipeContent: (body)  
     - returns: RequestBuilder<RecipeContent> 
     */
    open class func enrichRecipeWithRequestBuilder(recipeContent: RecipeContent) -> RequestBuilder<RecipeContent> {
        let localVariablePath = "/api/enrich"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: recipeContent)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RecipeContent>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
