//
// ImportAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ImportAPI {

    /**

     - parameter importFromPhotosRequest: (body)  
     - returns: ImportFromPhotosResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func importFromPhotos(importFromPhotosRequest: ImportFromPhotosRequest) async throws -> ImportFromPhotosResponse {
        return try await importFromPhotosWithRequestBuilder(importFromPhotosRequest: importFromPhotosRequest).execute().body
    }

    /**
     - POST /api/import/photos
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter importFromPhotosRequest: (body)  
     - returns: RequestBuilder<ImportFromPhotosResponse> 
     */
    open class func importFromPhotosWithRequestBuilder(importFromPhotosRequest: ImportFromPhotosRequest) -> RequestBuilder<ImportFromPhotosResponse> {
        let localVariablePath = "/api/import/photos"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: importFromPhotosRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImportFromPhotosResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter importRecipeRequest: (body)  
     - returns: ImportRecipeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func importRecipe(importRecipeRequest: ImportRecipeRequest) async throws -> ImportRecipeResponse {
        return try await importRecipeWithRequestBuilder(importRecipeRequest: importRecipeRequest).execute().body
    }

    /**
     - POST /api/import/recipe
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter importRecipeRequest: (body)  
     - returns: RequestBuilder<ImportRecipeResponse> 
     */
    open class func importRecipeWithRequestBuilder(importRecipeRequest: ImportRecipeRequest) -> RequestBuilder<ImportRecipeResponse> {
        let localVariablePath = "/api/import/recipe"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: importRecipeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImportRecipeResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter prepareTextRecipeRequest: (body)  
     - returns: PrepareTextRecipeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func prepareTextRecipe(prepareTextRecipeRequest: PrepareTextRecipeRequest) async throws -> PrepareTextRecipeResponse {
        return try await prepareTextRecipeWithRequestBuilder(prepareTextRecipeRequest: prepareTextRecipeRequest).execute().body
    }

    /**
     - POST /api/import/text
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter prepareTextRecipeRequest: (body)  
     - returns: RequestBuilder<PrepareTextRecipeResponse> 
     */
    open class func prepareTextRecipeWithRequestBuilder(prepareTextRecipeRequest: PrepareTextRecipeRequest) -> RequestBuilder<PrepareTextRecipeResponse> {
        let localVariablePath = "/api/import/text"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: prepareTextRecipeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PrepareTextRecipeResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
