//
// ImportAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ImportAPI {

    /**

     - parameter importRecipeRequest: (body)  
     - returns: ImportRecipeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func importRecipe(importRecipeRequest: ImportRecipeRequest) async throws -> ImportRecipeResponse {
        return try await importRecipeWithRequestBuilder(importRecipeRequest: importRecipeRequest).execute().body
    }

    /**
     - POST /api/import/recipe
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter importRecipeRequest: (body)  
     - returns: RequestBuilder<ImportRecipeResponse> 
     */
    open class func importRecipeWithRequestBuilder(importRecipeRequest: ImportRecipeRequest) -> RequestBuilder<ImportRecipeResponse> {
        let localVariablePath = "/api/import/recipe"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: importRecipeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ImportRecipeResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
