//
// IngredientNamesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class IngredientNamesAPI {

    /**

     - returns: IngredientNamesStatusResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getIngredientNamesStatus() async throws -> IngredientNamesStatusResponse {
        return try await getIngredientNamesStatusWithRequestBuilder().execute().body
    }

    /**
     - GET /api/ingredient-names/status
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - returns: RequestBuilder<IngredientNamesStatusResponse> 
     */
    open class func getIngredientNamesStatusWithRequestBuilder() -> RequestBuilder<IngredientNamesStatusResponse> {
        let localVariablePath = "/api/ingredient-names/status"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngredientNamesStatusResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: IngredientNamesQueuedResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func retryIngredientNames() async throws -> IngredientNamesQueuedResponse {
        return try await retryIngredientNamesWithRequestBuilder().execute().body
    }

    /**
     - POST /api/ingredient-names/retry
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - returns: RequestBuilder<IngredientNamesQueuedResponse> 
     */
    open class func retryIngredientNamesWithRequestBuilder() -> RequestBuilder<IngredientNamesQueuedResponse> {
        let localVariablePath = "/api/ingredient-names/retry"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<IngredientNamesQueuedResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
