//
// MealPlansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class MealPlansAPI {

    /**

     - parameter createMealPlanRequest: (body)  
     - returns: CreateMealPlanResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createMealPlan(createMealPlanRequest: CreateMealPlanRequest) async throws -> CreateMealPlanResponse {
        return try await createMealPlanWithRequestBuilder(createMealPlanRequest: createMealPlanRequest).execute().body
    }

    /**
     - POST /api/meal-plans
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter createMealPlanRequest: (body)  
     - returns: RequestBuilder<CreateMealPlanResponse> 
     */
    open class func createMealPlanWithRequestBuilder(createMealPlanRequest: CreateMealPlanRequest) -> RequestBuilder<CreateMealPlanResponse> {
        let localVariablePath = "/api/meal-plans"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createMealPlanRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateMealPlanResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Meal plan ID 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteMealPlan(id: UUID) async throws {
        return try await deleteMealPlanWithRequestBuilder(id: id).execute().body
    }

    /**
     - DELETE /api/meal-plans/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Meal plan ID 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteMealPlanWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/api/meal-plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = RamekinClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter startDate: (query) Start date (inclusive), format: YYYY-MM-DD. Defaults to today. (optional)
     - parameter endDate: (query) End date (inclusive), format: YYYY-MM-DD. Defaults to start_date + 6 days (one week). (optional)
     - returns: MealPlanListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listMealPlans(startDate: Date? = nil, endDate: Date? = nil) async throws -> MealPlanListResponse {
        return try await listMealPlansWithRequestBuilder(startDate: startDate, endDate: endDate).execute().body
    }

    /**
     - GET /api/meal-plans
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter startDate: (query) Start date (inclusive), format: YYYY-MM-DD. Defaults to today. (optional)
     - parameter endDate: (query) End date (inclusive), format: YYYY-MM-DD. Defaults to start_date + 6 days (one week). (optional)
     - returns: RequestBuilder<MealPlanListResponse> 
     */
    open class func listMealPlansWithRequestBuilder(startDate: Date? = nil, endDate: Date? = nil) -> RequestBuilder<MealPlanListResponse> {
        let localVariablePath = "/api/meal-plans"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "start_date": (wrappedValue: startDate?.encodeToJSON(), isExplode: true),
            "end_date": (wrappedValue: endDate?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MealPlanListResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Meal plan ID 
     - parameter updateMealPlanRequest: (body)  
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func updateMealPlan(id: UUID, updateMealPlanRequest: UpdateMealPlanRequest) async throws {
        return try await updateMealPlanWithRequestBuilder(id: id, updateMealPlanRequest: updateMealPlanRequest).execute().body
    }

    /**
     - PUT /api/meal-plans/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Meal plan ID 
     - parameter updateMealPlanRequest: (body)  
     - returns: RequestBuilder<Void> 
     */
    open class func updateMealPlanWithRequestBuilder(id: UUID, updateMealPlanRequest: UpdateMealPlanRequest) -> RequestBuilder<Void> {
        var localVariablePath = "/api/meal-plans/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateMealPlanRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = RamekinClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
