//
// PhotosAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class PhotosAPI {

    /**

     - parameter id: (path) Photo ID 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPhoto(id: UUID) async throws {
        return try await getPhotoWithRequestBuilder(id: id).execute().body
    }

    /**
     - GET /api/photos/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Photo ID 
     - returns: RequestBuilder<Void> 
     */
    open class func getPhotoWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/api/photos/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = RamekinClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Photo ID 
     - parameter size: (query) Desired thumbnail size in pixels (longest edge). Clamped to 1..&#x3D;800. Default: 200. (optional)
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getPhotoThumbnail(id: UUID, size: Int? = nil) async throws {
        return try await getPhotoThumbnailWithRequestBuilder(id: id, size: size).execute().body
    }

    /**
     - GET /api/photos/{id}/thumbnail
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Photo ID 
     - parameter size: (query) Desired thumbnail size in pixels (longest edge). Clamped to 1..&#x3D;800. Default: 200. (optional)
     - returns: RequestBuilder<Void> 
     */
    open class func getPhotoThumbnailWithRequestBuilder(id: UUID, size: Int? = nil) -> RequestBuilder<Void> {
        var localVariablePath = "/api/photos/{id}/thumbnail"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "size": (wrappedValue: size?.encodeToJSON(), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = RamekinClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter file: (form)  
     - returns: UploadPhotoResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func upload(file: URL) async throws -> UploadPhotoResponse {
        return try await uploadWithRequestBuilder(file: file).execute().body
    }

    /**
     - POST /api/photos
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter file: (form)  
     - returns: RequestBuilder<UploadPhotoResponse> 
     */
    open class func uploadWithRequestBuilder(file: URL) -> RequestBuilder<UploadPhotoResponse> {
        let localVariablePath = "/api/photos"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableFormParams: [String: Any?] = [
            "file": file.encodeToJSON(),
        ]

        let localVariableNonNullParameters = APIHelper.rejectNil(localVariableFormParams)
        let localVariableParameters = APIHelper.convertBoolToString(localVariableNonNullParameters)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "multipart/form-data",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UploadPhotoResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
