//
// ScrapeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class ScrapeAPI {

    /**

     - parameter captureRequest: (body)  
     - returns: CreateScrapeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func capture(captureRequest: CaptureRequest) async throws -> CreateScrapeResponse {
        return try await captureWithRequestBuilder(captureRequest: captureRequest).execute().body
    }

    /**
     - POST /api/scrape/capture
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter captureRequest: (body)  
     - returns: RequestBuilder<CreateScrapeResponse> 
     */
    open class func captureWithRequestBuilder(captureRequest: CaptureRequest) -> RequestBuilder<CreateScrapeResponse> {
        let localVariablePath = "/api/scrape/capture"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: captureRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateScrapeResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter createScrapeRequest: (body)  
     - returns: CreateScrapeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createScrape(createScrapeRequest: CreateScrapeRequest) async throws -> CreateScrapeResponse {
        return try await createScrapeWithRequestBuilder(createScrapeRequest: createScrapeRequest).execute().body
    }

    /**
     - POST /api/scrape
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter createScrapeRequest: (body)  
     - returns: RequestBuilder<CreateScrapeResponse> 
     */
    open class func createScrapeWithRequestBuilder(createScrapeRequest: CreateScrapeRequest) -> RequestBuilder<CreateScrapeResponse> {
        let localVariablePath = "/api/scrape"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createScrapeRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateScrapeResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Scrape job ID 
     - returns: ScrapeJobResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func getScrape(id: UUID) async throws -> ScrapeJobResponse {
        return try await getScrapeWithRequestBuilder(id: id).execute().body
    }

    /**
     - GET /api/scrape/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Scrape job ID 
     - returns: RequestBuilder<ScrapeJobResponse> 
     */
    open class func getScrapeWithRequestBuilder(id: UUID) -> RequestBuilder<ScrapeJobResponse> {
        var localVariablePath = "/api/scrape/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScrapeJobResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Scrape job ID 
     - returns: RetryScrapeResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func retryScrape(id: UUID) async throws -> RetryScrapeResponse {
        return try await retryScrapeWithRequestBuilder(id: id).execute().body
    }

    /**
     - POST /api/scrape/{id}/retry
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Scrape job ID 
     - returns: RequestBuilder<RetryScrapeResponse> 
     */
    open class func retryScrapeWithRequestBuilder(id: UUID) -> RequestBuilder<RetryScrapeResponse> {
        var localVariablePath = "/api/scrape/{id}/retry"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RetryScrapeResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
