//
// TagsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TagsAPI {

    /**

     - parameter createTagRequest: (body)  
     - returns: CreateTagResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func createTag(createTagRequest: CreateTagRequest) async throws -> CreateTagResponse {
        return try await createTagWithRequestBuilder(createTagRequest: createTagRequest).execute().body
    }

    /**
     - POST /api/tags
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter createTagRequest: (body)  
     - returns: RequestBuilder<CreateTagResponse> 
     */
    open class func createTagWithRequestBuilder(createTagRequest: CreateTagRequest) -> RequestBuilder<CreateTagResponse> {
        let localVariablePath = "/api/tags"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createTagRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CreateTagResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Tag ID 
     - returns: Void
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func deleteTag(id: UUID) async throws {
        return try await deleteTagWithRequestBuilder(id: id).execute().body
    }

    /**
     - DELETE /api/tags/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Tag ID 
     - returns: RequestBuilder<Void> 
     */
    open class func deleteTagWithRequestBuilder(id: UUID) -> RequestBuilder<Void> {
        var localVariablePath = "/api/tags/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = RamekinClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: TagsListResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func listAllTags() async throws -> TagsListResponse {
        return try await listAllTagsWithRequestBuilder().execute().body
    }

    /**
     - GET /api/tags
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - returns: RequestBuilder<TagsListResponse> 
     */
    open class func listAllTagsWithRequestBuilder() -> RequestBuilder<TagsListResponse> {
        let localVariablePath = "/api/tags"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TagsListResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter id: (path) Tag ID 
     - parameter renameTagRequest: (body)  
     - returns: RenameTagResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func renameTag(id: UUID, renameTagRequest: RenameTagRequest) async throws -> RenameTagResponse {
        return try await renameTagWithRequestBuilder(id: id, renameTagRequest: renameTagRequest).execute().body
    }

    /**
     - PATCH /api/tags/{id}
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - parameter id: (path) Tag ID 
     - parameter renameTagRequest: (body)  
     - returns: RequestBuilder<RenameTagResponse> 
     */
    open class func renameTagWithRequestBuilder(id: UUID, renameTagRequest: RenameTagRequest) -> RequestBuilder<RenameTagResponse> {
        var localVariablePath = "/api/tags/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: renameTagRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RenameTagResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PATCH", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
