//
// TestingAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class TestingAPI {

    /**

     - returns: PingResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func ping() async throws -> PingResponse {
        return try await pingWithRequestBuilder().execute().body
    }

    /**
     - GET /api/test/ping
     - Bearer Token:
       - type: http
       - name: bearer_auth
     - returns: RequestBuilder<PingResponse> 
     */
    open class func pingWithRequestBuilder() -> RequestBuilder<PingResponse> {
        let localVariablePath = "/api/test/ping"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PingResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - returns: UnauthedPingResponse
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func unauthedPing() async throws -> UnauthedPingResponse {
        return try await unauthedPingWithRequestBuilder().execute().body
    }

    /**
     - GET /api/test/unauthed-ping
     - returns: RequestBuilder<UnauthedPingResponse> 
     */
    open class func unauthedPingWithRequestBuilder() -> RequestBuilder<UnauthedPingResponse> {
        let localVariablePath = "/api/test/unauthed-ping"
        let localVariableURLString = RamekinClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UnauthedPingResponse>.Type = RamekinClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false)
    }
}
