version: "0.5"

log_configuration:
  disable_json: true
  no_color: true
  add_timestamp: true
  flush_each_line: true

processes:
  server:
    command: ${SERVER_CMD:-cargo run --release -q}
    readiness_probe:
      http_get:
        host: localhost
        port: ${PORT}
        path: /api/test/unauthed-ping
