version: "0.5"

log_configuration:
  disable_json: true
  no_color: true
  add_timestamp: true
  flush_each_line: true

processes:
  server:
    # Use SERVER_COMMAND env var if set (for CI with pre-built binary), else cargo run
    command: ${SERVER_COMMAND:-cargo run --release -q}
    readiness_probe:
      http_get:
        host: localhost
        port: ${PORT}
        path: /api/test/unauthed-ping
