#!/usr/bin/env bash
# Regenerate shared-test-vectors/search-normalization.json from the live
# PostgreSQL server: the complete per-codepoint unaccent dictionary mapping
# (the server's tsearch_data/unaccent.rules as actually applied by
# f_unaccent) plus the complete per-codepoint lower() case mapping that
# ILIKE and CITEXT comparisons use.
#
# Run against the dev database after a PostgreSQL upgrade and bump VERSION
# when the output changes; tests/test_search_normalization_contract.py fails
# when the checked-in asset drifts from the running server.
set -euo pipefail

DATABASE_URL="${DATABASE_URL:?set DATABASE_URL (see dev.env)}"
VERSION="${VERSION:?set VERSION to the normalization-contract version to stamp}"
OUT="$(cd "$(dirname "$0")/.." && pwd)/shared-test-vectors/search-normalization.json"

psql "$DATABASE_URL" -tA -v version="$VERSION" <<'SQL' > "$OUT"
with cps as (
  select cp from generate_series(1, 1114111) cp where cp < 55296 or cp > 57343
),
hex as (
  -- lpad truncates strings longer than the target length, so pad manually
  -- to keep supplementary-plane codepoints (5-digit hex) intact.
  select cp, repeat('0', greatest(0, 4 - length(to_hex(cp)))) || to_hex(cp) as key
  from cps
),
un as (
  select key, unaccent('public.unaccent', chr(cp)) as replacement
  from hex
  where unaccent('public.unaccent', chr(cp)) is distinct from chr(cp)
),
lo as (
  select key, lower(chr(cp)) as replacement
  from hex
  where lower(chr(cp)) is distinct from chr(cp)
)
select jsonb_pretty(jsonb_build_object(
  '_comment', 'Versioned search normalization contract. Generated by '
    || 'scripts/generate-search-normalization.sh; do not edit by hand. '
    || 'Keys are hex Unicode codepoints. "unaccent" is the complete mapping '
    || 'applied by the server''s f_unaccent (PostgreSQL unaccent.rules); '
    || '"lower" is the complete per-codepoint lower() mapping that ILIKE '
    || 'and CITEXT use. Bare-text matching and scoring normalize as '
    || 'lower(unaccent(text)); tag: equality uses lower() alone. The Rust '
    || 'and Swift normalizers consume this file, and recipe sync fails when '
    || 'client and server contract versions differ.',
  'version', :version,
  'unaccent', (select jsonb_object_agg(key, replacement) from un),
  'lower', (select jsonb_object_agg(key, replacement) from lo)
));
SQL

echo "wrote $OUT"
