/*
 * ramekin-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GarbagesResponse {
    #[serde(rename = "garbages")]
    pub garbages: Vec<String>,
}

impl GarbagesResponse {
    pub fn new(garbages: Vec<String>) -> GarbagesResponse {
        GarbagesResponse { garbages }
    }
}
