/*
 * ramekin-server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: your.email@example.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignupResponse {
    #[serde(rename = "token")]
    pub token: String,
    #[serde(rename = "user_id")]
    pub user_id: uuid::Uuid,
}

impl SignupResponse {
    pub fn new(token: String, user_id: uuid::Uuid) -> SignupResponse {
        SignupResponse {
            token,
            user_id,
        }
    }
}

